// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/way2we/way2we_api/ent/agreement"
	"github.com/way2we/way2we_api/ent/group"
	"github.com/way2we/way2we_api/ent/user"
)

// Agreement is the model entity for the Agreement schema.
type Agreement struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Agreement name, 1-50 characters
	Name string `json:"name,omitempty"`
	// Agreement description, optional, max 200 characters
	Description string `json:"description,omitempty"`
	// Points for completing this agreement, 1-99999
	Points int `json:"points,omitempty"`
	// Whether completion requires confirmation
	RequireConfirmation bool `json:"require_confirmation,omitempty"`
	// Optional cover image URL
	CoverImageURL *string `json:"cover_image_url,omitempty"`
	// Agreement status: active or inactive
	Status agreement.Status `json:"status,omitempty"`
	// Foreign key to Group
	GroupID int `json:"group_id,omitempty"`
	// Foreign key to User who created this agreement
	CreatorID int `json:"creator_id,omitempty"`
	// List of member IDs this agreement applies to, empty means all members
	ApplicableMemberIds []int `json:"applicable_member_ids,omitempty"`
	// Agreement creation timestamp
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Last update timestamp
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AgreementQuery when eager-loading is set.
	Edges        AgreementEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AgreementEdges holds the relations/edges for other nodes in the graph.
type AgreementEdges struct {
	// The group this agreement belongs to
	Group *Group `json:"group,omitempty"`
	// The user who created this agreement
	Creator *User `json:"creator,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AgreementEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// CreatorOrErr returns the Creator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AgreementEdges) CreatorOrErr() (*User, error) {
	if e.Creator != nil {
		return e.Creator, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "creator"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Agreement) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case agreement.FieldApplicableMemberIds:
			values[i] = new([]byte)
		case agreement.FieldRequireConfirmation:
			values[i] = new(sql.NullBool)
		case agreement.FieldID, agreement.FieldPoints, agreement.FieldGroupID, agreement.FieldCreatorID:
			values[i] = new(sql.NullInt64)
		case agreement.FieldName, agreement.FieldDescription, agreement.FieldCoverImageURL, agreement.FieldStatus:
			values[i] = new(sql.NullString)
		case agreement.FieldCreatedAt, agreement.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Agreement fields.
func (_m *Agreement) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case agreement.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case agreement.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case agreement.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case agreement.FieldPoints:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field points", values[i])
			} else if value.Valid {
				_m.Points = int(value.Int64)
			}
		case agreement.FieldRequireConfirmation:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field require_confirmation", values[i])
			} else if value.Valid {
				_m.RequireConfirmation = value.Bool
			}
		case agreement.FieldCoverImageURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cover_image_url", values[i])
			} else if value.Valid {
				_m.CoverImageURL = new(string)
				*_m.CoverImageURL = value.String
			}
		case agreement.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = agreement.Status(value.String)
			}
		case agreement.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = int(value.Int64)
			}
		case agreement.FieldCreatorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field creator_id", values[i])
			} else if value.Valid {
				_m.CreatorID = int(value.Int64)
			}
		case agreement.FieldApplicableMemberIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field applicable_member_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ApplicableMemberIds); err != nil {
					return fmt.Errorf("unmarshal field applicable_member_ids: %w", err)
				}
			}
		case agreement.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case agreement.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Agreement.
// This includes values selected through modifiers, order, etc.
func (_m *Agreement) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the Agreement entity.
func (_m *Agreement) QueryGroup() *GroupQuery {
	return NewAgreementClient(_m.config).QueryGroup(_m)
}

// QueryCreator queries the "creator" edge of the Agreement entity.
func (_m *Agreement) QueryCreator() *UserQuery {
	return NewAgreementClient(_m.config).QueryCreator(_m)
}

// Update returns a builder for updating this Agreement.
// Note that you need to call Agreement.Unwrap() before calling this method if this Agreement
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Agreement) Update() *AgreementUpdateOne {
	return NewAgreementClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Agreement entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Agreement) Unwrap() *Agreement {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Agreement is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Agreement) String() string {
	var builder strings.Builder
	builder.WriteString("Agreement(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("points=")
	builder.WriteString(fmt.Sprintf("%v", _m.Points))
	builder.WriteString(", ")
	builder.WriteString("require_confirmation=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequireConfirmation))
	builder.WriteString(", ")
	if v := _m.CoverImageURL; v != nil {
		builder.WriteString("cover_image_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("creator_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatorID))
	builder.WriteString(", ")
	builder.WriteString("applicable_member_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.ApplicableMemberIds))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Agreements is a parsable slice of Agreement.
type Agreements []*Agreement
