// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/way2we/way2we_api/ent/agreementcompletion"
	"github.com/way2we/way2we_api/ent/predicate"
)

// AgreementCompletionDelete is the builder for deleting a AgreementCompletion entity.
type AgreementCompletionDelete struct {
	config
	hooks    []Hook
	mutation *AgreementCompletionMutation
}

// Where appends a list predicates to the AgreementCompletionDelete builder.
func (_d *AgreementCompletionDelete) Where(ps ...predicate.AgreementCompletion) *AgreementCompletionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AgreementCompletionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AgreementCompletionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AgreementCompletionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(agreementcompletion.Table, sqlgraph.NewFieldSpec(agreementcompletion.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AgreementCompletionDeleteOne is the builder for deleting a single AgreementCompletion entity.
type AgreementCompletionDeleteOne struct {
	_d *AgreementCompletionDelete
}

// Where appends a list predicates to the AgreementCompletionDelete builder.
func (_d *AgreementCompletionDeleteOne) Where(ps ...predicate.AgreementCompletion) *AgreementCompletionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AgreementCompletionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{agreementcompletion.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AgreementCompletionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
