// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/way2we/way2we_api/ent/agreement"
	"github.com/way2we/way2we_api/ent/group"
	"github.com/way2we/way2we_api/ent/user"
)

// AgreementCreate is the builder for creating a Agreement entity.
type AgreementCreate struct {
	config
	mutation *AgreementMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *AgreementCreate) SetName(v string) *AgreementCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *AgreementCreate) SetDescription(v string) *AgreementCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *AgreementCreate) SetNillableDescription(v *string) *AgreementCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetPoints sets the "points" field.
func (_c *AgreementCreate) SetPoints(v int) *AgreementCreate {
	_c.mutation.SetPoints(v)
	return _c
}

// SetRequireConfirmation sets the "require_confirmation" field.
func (_c *AgreementCreate) SetRequireConfirmation(v bool) *AgreementCreate {
	_c.mutation.SetRequireConfirmation(v)
	return _c
}

// SetNillableRequireConfirmation sets the "require_confirmation" field if the given value is not nil.
func (_c *AgreementCreate) SetNillableRequireConfirmation(v *bool) *AgreementCreate {
	if v != nil {
		_c.SetRequireConfirmation(*v)
	}
	return _c
}

// SetCoverImageURL sets the "cover_image_url" field.
func (_c *AgreementCreate) SetCoverImageURL(v string) *AgreementCreate {
	_c.mutation.SetCoverImageURL(v)
	return _c
}

// SetNillableCoverImageURL sets the "cover_image_url" field if the given value is not nil.
func (_c *AgreementCreate) SetNillableCoverImageURL(v *string) *AgreementCreate {
	if v != nil {
		_c.SetCoverImageURL(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *AgreementCreate) SetStatus(v agreement.Status) *AgreementCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AgreementCreate) SetNillableStatus(v *agreement.Status) *AgreementCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *AgreementCreate) SetGroupID(v int) *AgreementCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetCreatorID sets the "creator_id" field.
func (_c *AgreementCreate) SetCreatorID(v int) *AgreementCreate {
	_c.mutation.SetCreatorID(v)
	return _c
}

// SetApplicableMemberIds sets the "applicable_member_ids" field.
func (_c *AgreementCreate) SetApplicableMemberIds(v []int) *AgreementCreate {
	_c.mutation.SetApplicableMemberIds(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AgreementCreate) SetCreatedAt(v time.Time) *AgreementCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AgreementCreate) SetNillableCreatedAt(v *time.Time) *AgreementCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AgreementCreate) SetUpdatedAt(v time.Time) *AgreementCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AgreementCreate) SetNillableUpdatedAt(v *time.Time) *AgreementCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *AgreementCreate) SetGroup(v *Group) *AgreementCreate {
	return _c.SetGroupID(v.ID)
}

// SetCreator sets the "creator" edge to the User entity.
func (_c *AgreementCreate) SetCreator(v *User) *AgreementCreate {
	return _c.SetCreatorID(v.ID)
}

// AddPinnedByUserIDs adds the "pinned_by_users" edge to the User entity by IDs.
func (_c *AgreementCreate) AddPinnedByUserIDs(ids ...int) *AgreementCreate {
	_c.mutation.AddPinnedByUserIDs(ids...)
	return _c
}

// AddPinnedByUsers adds the "pinned_by_users" edges to the User entity.
func (_c *AgreementCreate) AddPinnedByUsers(v ...*User) *AgreementCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPinnedByUserIDs(ids...)
}

// Mutation returns the AgreementMutation object of the builder.
func (_c *AgreementCreate) Mutation() *AgreementMutation {
	return _c.mutation
}

// Save creates the Agreement in the database.
func (_c *AgreementCreate) Save(ctx context.Context) (*Agreement, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AgreementCreate) SaveX(ctx context.Context) *Agreement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgreementCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgreementCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AgreementCreate) defaults() {
	if _, ok := _c.mutation.RequireConfirmation(); !ok {
		v := agreement.DefaultRequireConfirmation
		_c.mutation.SetRequireConfirmation(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := agreement.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := agreement.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := agreement.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AgreementCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Agreement.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := agreement.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Agreement.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := agreement.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Agreement.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Points(); !ok {
		return &ValidationError{Name: "points", err: errors.New(`ent: missing required field "Agreement.points"`)}
	}
	if v, ok := _c.mutation.Points(); ok {
		if err := agreement.PointsValidator(v); err != nil {
			return &ValidationError{Name: "points", err: fmt.Errorf(`ent: validator failed for field "Agreement.points": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequireConfirmation(); !ok {
		return &ValidationError{Name: "require_confirmation", err: errors.New(`ent: missing required field "Agreement.require_confirmation"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Agreement.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := agreement.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Agreement.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "Agreement.group_id"`)}
	}
	if _, ok := _c.mutation.CreatorID(); !ok {
		return &ValidationError{Name: "creator_id", err: errors.New(`ent: missing required field "Agreement.creator_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Agreement.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Agreement.updated_at"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "Agreement.group"`)}
	}
	if len(_c.mutation.CreatorIDs()) == 0 {
		return &ValidationError{Name: "creator", err: errors.New(`ent: missing required edge "Agreement.creator"`)}
	}
	return nil
}

func (_c *AgreementCreate) sqlSave(ctx context.Context) (*Agreement, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AgreementCreate) createSpec() (*Agreement, *sqlgraph.CreateSpec) {
	var (
		_node = &Agreement{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(agreement.Table, sqlgraph.NewFieldSpec(agreement.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(agreement.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(agreement.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Points(); ok {
		_spec.SetField(agreement.FieldPoints, field.TypeInt, value)
		_node.Points = value
	}
	if value, ok := _c.mutation.RequireConfirmation(); ok {
		_spec.SetField(agreement.FieldRequireConfirmation, field.TypeBool, value)
		_node.RequireConfirmation = value
	}
	if value, ok := _c.mutation.CoverImageURL(); ok {
		_spec.SetField(agreement.FieldCoverImageURL, field.TypeString, value)
		_node.CoverImageURL = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(agreement.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ApplicableMemberIds(); ok {
		_spec.SetField(agreement.FieldApplicableMemberIds, field.TypeJSON, value)
		_node.ApplicableMemberIds = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(agreement.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(agreement.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agreement.GroupTable,
			Columns: []string{agreement.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   agreement.CreatorTable,
			Columns: []string{agreement.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatorID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PinnedByUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   agreement.PinnedByUsersTable,
			Columns: agreement.PinnedByUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AgreementCreateBulk is the builder for creating many Agreement entities in bulk.
type AgreementCreateBulk struct {
	config
	err      error
	builders []*AgreementCreate
}

// Save creates the Agreement entities in the database.
func (_c *AgreementCreateBulk) Save(ctx context.Context) ([]*Agreement, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Agreement, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgreementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AgreementCreateBulk) SaveX(ctx context.Context) []*Agreement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgreementCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgreementCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
