// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/way2we/way2we_api/ent/agreement"
	"github.com/way2we/way2we_api/ent/group"
	"github.com/way2we/way2we_api/ent/groupmember"
	"github.com/way2we/way2we_api/ent/membersummary"
	"github.com/way2we/way2we_api/ent/pointlog"
	"github.com/way2we/way2we_api/ent/predicate"
	"github.com/way2we/way2we_api/ent/reward"
)

// GroupUpdate is the builder for updating Group entities.
type GroupUpdate struct {
	config
	hooks    []Hook
	mutation *GroupMutation
}

// Where appends a list predicates to the GroupUpdate builder.
func (_u *GroupUpdate) Where(ps ...predicate.Group) *GroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *GroupUpdate) SetName(v string) *GroupUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableName(v *string) *GroupUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *GroupUpdate) SetDescription(v string) *GroupUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableDescription(v *string) *GroupUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *GroupUpdate) ClearDescription() *GroupUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetInvitationCode sets the "invitation_code" field.
func (_u *GroupUpdate) SetInvitationCode(v string) *GroupUpdate {
	_u.mutation.SetInvitationCode(v)
	return _u
}

// SetNillableInvitationCode sets the "invitation_code" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableInvitationCode(v *string) *GroupUpdate {
	if v != nil {
		_u.SetInvitationCode(*v)
	}
	return _u
}

// ClearInvitationCode clears the value of the "invitation_code" field.
func (_u *GroupUpdate) ClearInvitationCode() *GroupUpdate {
	_u.mutation.ClearInvitationCode()
	return _u
}

// SetRequireConfirmationDefault sets the "require_confirmation_default" field.
func (_u *GroupUpdate) SetRequireConfirmationDefault(v bool) *GroupUpdate {
	_u.mutation.SetRequireConfirmationDefault(v)
	return _u
}

// SetNillableRequireConfirmationDefault sets the "require_confirmation_default" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableRequireConfirmationDefault(v *bool) *GroupUpdate {
	if v != nil {
		_u.SetRequireConfirmationDefault(*v)
	}
	return _u
}

// SetAutoCompleteRedemptionDefault sets the "auto_complete_redemption_default" field.
func (_u *GroupUpdate) SetAutoCompleteRedemptionDefault(v bool) *GroupUpdate {
	_u.mutation.SetAutoCompleteRedemptionDefault(v)
	return _u
}

// SetNillableAutoCompleteRedemptionDefault sets the "auto_complete_redemption_default" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableAutoCompleteRedemptionDefault(v *bool) *GroupUpdate {
	if v != nil {
		_u.SetAutoCompleteRedemptionDefault(*v)
	}
	return _u
}

// SetAutoFulfillRedemptionDefault sets the "auto_fulfill_redemption_default" field.
func (_u *GroupUpdate) SetAutoFulfillRedemptionDefault(v bool) *GroupUpdate {
	_u.mutation.SetAutoFulfillRedemptionDefault(v)
	return _u
}

// SetNillableAutoFulfillRedemptionDefault sets the "auto_fulfill_redemption_default" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableAutoFulfillRedemptionDefault(v *bool) *GroupUpdate {
	if v != nil {
		_u.SetAutoFulfillRedemptionDefault(*v)
	}
	return _u
}

// SetProviderIncentiveRatio sets the "provider_incentive_ratio" field.
func (_u *GroupUpdate) SetProviderIncentiveRatio(v int) *GroupUpdate {
	_u.mutation.ResetProviderIncentiveRatio()
	_u.mutation.SetProviderIncentiveRatio(v)
	return _u
}

// SetNillableProviderIncentiveRatio sets the "provider_incentive_ratio" field if the given value is not nil.
func (_u *GroupUpdate) SetNillableProviderIncentiveRatio(v *int) *GroupUpdate {
	if v != nil {
		_u.SetProviderIncentiveRatio(*v)
	}
	return _u
}

// AddProviderIncentiveRatio adds value to the "provider_incentive_ratio" field.
func (_u *GroupUpdate) AddProviderIncentiveRatio(v int) *GroupUpdate {
	_u.mutation.AddProviderIncentiveRatio(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupUpdate) SetUpdatedAt(v time.Time) *GroupUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddMemberIDs adds the "members" edge to the GroupMember entity by IDs.
func (_u *GroupUpdate) AddMemberIDs(ids ...int) *GroupUpdate {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the GroupMember entity.
func (_u *GroupUpdate) AddMembers(v ...*GroupMember) *GroupUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// AddAgreementIDs adds the "agreements" edge to the Agreement entity by IDs.
func (_u *GroupUpdate) AddAgreementIDs(ids ...int) *GroupUpdate {
	_u.mutation.AddAgreementIDs(ids...)
	return _u
}

// AddAgreements adds the "agreements" edges to the Agreement entity.
func (_u *GroupUpdate) AddAgreements(v ...*Agreement) *GroupUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAgreementIDs(ids...)
}

// AddRewardIDs adds the "rewards" edge to the Reward entity by IDs.
func (_u *GroupUpdate) AddRewardIDs(ids ...int) *GroupUpdate {
	_u.mutation.AddRewardIDs(ids...)
	return _u
}

// AddRewards adds the "rewards" edges to the Reward entity.
func (_u *GroupUpdate) AddRewards(v ...*Reward) *GroupUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRewardIDs(ids...)
}

// AddPointLogIDs adds the "point_logs" edge to the PointLog entity by IDs.
func (_u *GroupUpdate) AddPointLogIDs(ids ...int) *GroupUpdate {
	_u.mutation.AddPointLogIDs(ids...)
	return _u
}

// AddPointLogs adds the "point_logs" edges to the PointLog entity.
func (_u *GroupUpdate) AddPointLogs(v ...*PointLog) *GroupUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPointLogIDs(ids...)
}

// AddMemberSummaryIDs adds the "member_summaries" edge to the MemberSummary entity by IDs.
func (_u *GroupUpdate) AddMemberSummaryIDs(ids ...int) *GroupUpdate {
	_u.mutation.AddMemberSummaryIDs(ids...)
	return _u
}

// AddMemberSummaries adds the "member_summaries" edges to the MemberSummary entity.
func (_u *GroupUpdate) AddMemberSummaries(v ...*MemberSummary) *GroupUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberSummaryIDs(ids...)
}

// Mutation returns the GroupMutation object of the builder.
func (_u *GroupUpdate) Mutation() *GroupMutation {
	return _u.mutation
}

// ClearMembers clears all "members" edges to the GroupMember entity.
func (_u *GroupUpdate) ClearMembers() *GroupUpdate {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to GroupMember entities by IDs.
func (_u *GroupUpdate) RemoveMemberIDs(ids ...int) *GroupUpdate {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to GroupMember entities.
func (_u *GroupUpdate) RemoveMembers(v ...*GroupMember) *GroupUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// ClearAgreements clears all "agreements" edges to the Agreement entity.
func (_u *GroupUpdate) ClearAgreements() *GroupUpdate {
	_u.mutation.ClearAgreements()
	return _u
}

// RemoveAgreementIDs removes the "agreements" edge to Agreement entities by IDs.
func (_u *GroupUpdate) RemoveAgreementIDs(ids ...int) *GroupUpdate {
	_u.mutation.RemoveAgreementIDs(ids...)
	return _u
}

// RemoveAgreements removes "agreements" edges to Agreement entities.
func (_u *GroupUpdate) RemoveAgreements(v ...*Agreement) *GroupUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAgreementIDs(ids...)
}

// ClearRewards clears all "rewards" edges to the Reward entity.
func (_u *GroupUpdate) ClearRewards() *GroupUpdate {
	_u.mutation.ClearRewards()
	return _u
}

// RemoveRewardIDs removes the "rewards" edge to Reward entities by IDs.
func (_u *GroupUpdate) RemoveRewardIDs(ids ...int) *GroupUpdate {
	_u.mutation.RemoveRewardIDs(ids...)
	return _u
}

// RemoveRewards removes "rewards" edges to Reward entities.
func (_u *GroupUpdate) RemoveRewards(v ...*Reward) *GroupUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRewardIDs(ids...)
}

// ClearPointLogs clears all "point_logs" edges to the PointLog entity.
func (_u *GroupUpdate) ClearPointLogs() *GroupUpdate {
	_u.mutation.ClearPointLogs()
	return _u
}

// RemovePointLogIDs removes the "point_logs" edge to PointLog entities by IDs.
func (_u *GroupUpdate) RemovePointLogIDs(ids ...int) *GroupUpdate {
	_u.mutation.RemovePointLogIDs(ids...)
	return _u
}

// RemovePointLogs removes "point_logs" edges to PointLog entities.
func (_u *GroupUpdate) RemovePointLogs(v ...*PointLog) *GroupUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePointLogIDs(ids...)
}

// ClearMemberSummaries clears all "member_summaries" edges to the MemberSummary entity.
func (_u *GroupUpdate) ClearMemberSummaries() *GroupUpdate {
	_u.mutation.ClearMemberSummaries()
	return _u
}

// RemoveMemberSummaryIDs removes the "member_summaries" edge to MemberSummary entities by IDs.
func (_u *GroupUpdate) RemoveMemberSummaryIDs(ids ...int) *GroupUpdate {
	_u.mutation.RemoveMemberSummaryIDs(ids...)
	return _u
}

// RemoveMemberSummaries removes "member_summaries" edges to MemberSummary entities.
func (_u *GroupUpdate) RemoveMemberSummaries(v ...*MemberSummary) *GroupUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberSummaryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GroupUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GroupUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := group.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := group.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Group.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := group.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Group.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InvitationCode(); ok {
		if err := group.InvitationCodeValidator(v); err != nil {
			return &ValidationError{Name: "invitation_code", err: fmt.Errorf(`ent: validator failed for field "Group.invitation_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderIncentiveRatio(); ok {
		if err := group.ProviderIncentiveRatioValidator(v); err != nil {
			return &ValidationError{Name: "provider_incentive_ratio", err: fmt.Errorf(`ent: validator failed for field "Group.provider_incentive_ratio": %w`, err)}
		}
	}
	return nil
}

func (_u *GroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(group.Table, group.Columns, sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(group.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(group.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(group.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.InvitationCode(); ok {
		_spec.SetField(group.FieldInvitationCode, field.TypeString, value)
	}
	if _u.mutation.InvitationCodeCleared() {
		_spec.ClearField(group.FieldInvitationCode, field.TypeString)
	}
	if value, ok := _u.mutation.RequireConfirmationDefault(); ok {
		_spec.SetField(group.FieldRequireConfirmationDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AutoCompleteRedemptionDefault(); ok {
		_spec.SetField(group.FieldAutoCompleteRedemptionDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AutoFulfillRedemptionDefault(); ok {
		_spec.SetField(group.FieldAutoFulfillRedemptionDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ProviderIncentiveRatio(); ok {
		_spec.SetField(group.FieldProviderIncentiveRatio, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProviderIncentiveRatio(); ok {
		_spec.AddField(group.FieldProviderIncentiveRatio, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(group.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.MembersTable,
			Columns: []string{group.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupmember.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.MembersTable,
			Columns: []string{group.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupmember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.MembersTable,
			Columns: []string{group.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupmember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AgreementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.AgreementsTable,
			Columns: []string{group.AgreementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agreement.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAgreementsIDs(); len(nodes) > 0 && !_u.mutation.AgreementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.AgreementsTable,
			Columns: []string{group.AgreementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agreement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgreementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.AgreementsTable,
			Columns: []string{group.AgreementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agreement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RewardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.RewardsTable,
			Columns: []string{group.RewardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reward.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRewardsIDs(); len(nodes) > 0 && !_u.mutation.RewardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.RewardsTable,
			Columns: []string{group.RewardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reward.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RewardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.RewardsTable,
			Columns: []string{group.RewardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reward.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PointLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.PointLogsTable,
			Columns: []string{group.PointLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pointlog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPointLogsIDs(); len(nodes) > 0 && !_u.mutation.PointLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.PointLogsTable,
			Columns: []string{group.PointLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pointlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PointLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.PointLogsTable,
			Columns: []string{group.PointLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pointlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MemberSummariesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.MemberSummariesTable,
			Columns: []string{group.MemberSummariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membersummary.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMemberSummariesIDs(); len(nodes) > 0 && !_u.mutation.MemberSummariesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.MemberSummariesTable,
			Columns: []string{group.MemberSummariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membersummary.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberSummariesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.MemberSummariesTable,
			Columns: []string{group.MemberSummariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membersummary.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{group.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GroupUpdateOne is the builder for updating a single Group entity.
type GroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroupMutation
}

// SetName sets the "name" field.
func (_u *GroupUpdateOne) SetName(v string) *GroupUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableName(v *string) *GroupUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *GroupUpdateOne) SetDescription(v string) *GroupUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableDescription(v *string) *GroupUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *GroupUpdateOne) ClearDescription() *GroupUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetInvitationCode sets the "invitation_code" field.
func (_u *GroupUpdateOne) SetInvitationCode(v string) *GroupUpdateOne {
	_u.mutation.SetInvitationCode(v)
	return _u
}

// SetNillableInvitationCode sets the "invitation_code" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableInvitationCode(v *string) *GroupUpdateOne {
	if v != nil {
		_u.SetInvitationCode(*v)
	}
	return _u
}

// ClearInvitationCode clears the value of the "invitation_code" field.
func (_u *GroupUpdateOne) ClearInvitationCode() *GroupUpdateOne {
	_u.mutation.ClearInvitationCode()
	return _u
}

// SetRequireConfirmationDefault sets the "require_confirmation_default" field.
func (_u *GroupUpdateOne) SetRequireConfirmationDefault(v bool) *GroupUpdateOne {
	_u.mutation.SetRequireConfirmationDefault(v)
	return _u
}

// SetNillableRequireConfirmationDefault sets the "require_confirmation_default" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableRequireConfirmationDefault(v *bool) *GroupUpdateOne {
	if v != nil {
		_u.SetRequireConfirmationDefault(*v)
	}
	return _u
}

// SetAutoCompleteRedemptionDefault sets the "auto_complete_redemption_default" field.
func (_u *GroupUpdateOne) SetAutoCompleteRedemptionDefault(v bool) *GroupUpdateOne {
	_u.mutation.SetAutoCompleteRedemptionDefault(v)
	return _u
}

// SetNillableAutoCompleteRedemptionDefault sets the "auto_complete_redemption_default" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableAutoCompleteRedemptionDefault(v *bool) *GroupUpdateOne {
	if v != nil {
		_u.SetAutoCompleteRedemptionDefault(*v)
	}
	return _u
}

// SetAutoFulfillRedemptionDefault sets the "auto_fulfill_redemption_default" field.
func (_u *GroupUpdateOne) SetAutoFulfillRedemptionDefault(v bool) *GroupUpdateOne {
	_u.mutation.SetAutoFulfillRedemptionDefault(v)
	return _u
}

// SetNillableAutoFulfillRedemptionDefault sets the "auto_fulfill_redemption_default" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableAutoFulfillRedemptionDefault(v *bool) *GroupUpdateOne {
	if v != nil {
		_u.SetAutoFulfillRedemptionDefault(*v)
	}
	return _u
}

// SetProviderIncentiveRatio sets the "provider_incentive_ratio" field.
func (_u *GroupUpdateOne) SetProviderIncentiveRatio(v int) *GroupUpdateOne {
	_u.mutation.ResetProviderIncentiveRatio()
	_u.mutation.SetProviderIncentiveRatio(v)
	return _u
}

// SetNillableProviderIncentiveRatio sets the "provider_incentive_ratio" field if the given value is not nil.
func (_u *GroupUpdateOne) SetNillableProviderIncentiveRatio(v *int) *GroupUpdateOne {
	if v != nil {
		_u.SetProviderIncentiveRatio(*v)
	}
	return _u
}

// AddProviderIncentiveRatio adds value to the "provider_incentive_ratio" field.
func (_u *GroupUpdateOne) AddProviderIncentiveRatio(v int) *GroupUpdateOne {
	_u.mutation.AddProviderIncentiveRatio(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupUpdateOne) SetUpdatedAt(v time.Time) *GroupUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddMemberIDs adds the "members" edge to the GroupMember entity by IDs.
func (_u *GroupUpdateOne) AddMemberIDs(ids ...int) *GroupUpdateOne {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the GroupMember entity.
func (_u *GroupUpdateOne) AddMembers(v ...*GroupMember) *GroupUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// AddAgreementIDs adds the "agreements" edge to the Agreement entity by IDs.
func (_u *GroupUpdateOne) AddAgreementIDs(ids ...int) *GroupUpdateOne {
	_u.mutation.AddAgreementIDs(ids...)
	return _u
}

// AddAgreements adds the "agreements" edges to the Agreement entity.
func (_u *GroupUpdateOne) AddAgreements(v ...*Agreement) *GroupUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAgreementIDs(ids...)
}

// AddRewardIDs adds the "rewards" edge to the Reward entity by IDs.
func (_u *GroupUpdateOne) AddRewardIDs(ids ...int) *GroupUpdateOne {
	_u.mutation.AddRewardIDs(ids...)
	return _u
}

// AddRewards adds the "rewards" edges to the Reward entity.
func (_u *GroupUpdateOne) AddRewards(v ...*Reward) *GroupUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRewardIDs(ids...)
}

// AddPointLogIDs adds the "point_logs" edge to the PointLog entity by IDs.
func (_u *GroupUpdateOne) AddPointLogIDs(ids ...int) *GroupUpdateOne {
	_u.mutation.AddPointLogIDs(ids...)
	return _u
}

// AddPointLogs adds the "point_logs" edges to the PointLog entity.
func (_u *GroupUpdateOne) AddPointLogs(v ...*PointLog) *GroupUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPointLogIDs(ids...)
}

// AddMemberSummaryIDs adds the "member_summaries" edge to the MemberSummary entity by IDs.
func (_u *GroupUpdateOne) AddMemberSummaryIDs(ids ...int) *GroupUpdateOne {
	_u.mutation.AddMemberSummaryIDs(ids...)
	return _u
}

// AddMemberSummaries adds the "member_summaries" edges to the MemberSummary entity.
func (_u *GroupUpdateOne) AddMemberSummaries(v ...*MemberSummary) *GroupUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberSummaryIDs(ids...)
}

// Mutation returns the GroupMutation object of the builder.
func (_u *GroupUpdateOne) Mutation() *GroupMutation {
	return _u.mutation
}

// ClearMembers clears all "members" edges to the GroupMember entity.
func (_u *GroupUpdateOne) ClearMembers() *GroupUpdateOne {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to GroupMember entities by IDs.
func (_u *GroupUpdateOne) RemoveMemberIDs(ids ...int) *GroupUpdateOne {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to GroupMember entities.
func (_u *GroupUpdateOne) RemoveMembers(v ...*GroupMember) *GroupUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// ClearAgreements clears all "agreements" edges to the Agreement entity.
func (_u *GroupUpdateOne) ClearAgreements() *GroupUpdateOne {
	_u.mutation.ClearAgreements()
	return _u
}

// RemoveAgreementIDs removes the "agreements" edge to Agreement entities by IDs.
func (_u *GroupUpdateOne) RemoveAgreementIDs(ids ...int) *GroupUpdateOne {
	_u.mutation.RemoveAgreementIDs(ids...)
	return _u
}

// RemoveAgreements removes "agreements" edges to Agreement entities.
func (_u *GroupUpdateOne) RemoveAgreements(v ...*Agreement) *GroupUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAgreementIDs(ids...)
}

// ClearRewards clears all "rewards" edges to the Reward entity.
func (_u *GroupUpdateOne) ClearRewards() *GroupUpdateOne {
	_u.mutation.ClearRewards()
	return _u
}

// RemoveRewardIDs removes the "rewards" edge to Reward entities by IDs.
func (_u *GroupUpdateOne) RemoveRewardIDs(ids ...int) *GroupUpdateOne {
	_u.mutation.RemoveRewardIDs(ids...)
	return _u
}

// RemoveRewards removes "rewards" edges to Reward entities.
func (_u *GroupUpdateOne) RemoveRewards(v ...*Reward) *GroupUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRewardIDs(ids...)
}

// ClearPointLogs clears all "point_logs" edges to the PointLog entity.
func (_u *GroupUpdateOne) ClearPointLogs() *GroupUpdateOne {
	_u.mutation.ClearPointLogs()
	return _u
}

// RemovePointLogIDs removes the "point_logs" edge to PointLog entities by IDs.
func (_u *GroupUpdateOne) RemovePointLogIDs(ids ...int) *GroupUpdateOne {
	_u.mutation.RemovePointLogIDs(ids...)
	return _u
}

// RemovePointLogs removes "point_logs" edges to PointLog entities.
func (_u *GroupUpdateOne) RemovePointLogs(v ...*PointLog) *GroupUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePointLogIDs(ids...)
}

// ClearMemberSummaries clears all "member_summaries" edges to the MemberSummary entity.
func (_u *GroupUpdateOne) ClearMemberSummaries() *GroupUpdateOne {
	_u.mutation.ClearMemberSummaries()
	return _u
}

// RemoveMemberSummaryIDs removes the "member_summaries" edge to MemberSummary entities by IDs.
func (_u *GroupUpdateOne) RemoveMemberSummaryIDs(ids ...int) *GroupUpdateOne {
	_u.mutation.RemoveMemberSummaryIDs(ids...)
	return _u
}

// RemoveMemberSummaries removes "member_summaries" edges to MemberSummary entities.
func (_u *GroupUpdateOne) RemoveMemberSummaries(v ...*MemberSummary) *GroupUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberSummaryIDs(ids...)
}

// Where appends a list predicates to the GroupUpdate builder.
func (_u *GroupUpdateOne) Where(ps ...predicate.Group) *GroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GroupUpdateOne) Select(field string, fields ...string) *GroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Group entity.
func (_u *GroupUpdateOne) Save(ctx context.Context) (*Group, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupUpdateOne) SaveX(ctx context.Context) *Group {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GroupUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := group.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := group.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Group.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := group.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Group.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InvitationCode(); ok {
		if err := group.InvitationCodeValidator(v); err != nil {
			return &ValidationError{Name: "invitation_code", err: fmt.Errorf(`ent: validator failed for field "Group.invitation_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderIncentiveRatio(); ok {
		if err := group.ProviderIncentiveRatioValidator(v); err != nil {
			return &ValidationError{Name: "provider_incentive_ratio", err: fmt.Errorf(`ent: validator failed for field "Group.provider_incentive_ratio": %w`, err)}
		}
	}
	return nil
}

func (_u *GroupUpdateOne) sqlSave(ctx context.Context) (_node *Group, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(group.Table, group.Columns, sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Group.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, group.FieldID)
		for _, f := range fields {
			if !group.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != group.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(group.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(group.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(group.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.InvitationCode(); ok {
		_spec.SetField(group.FieldInvitationCode, field.TypeString, value)
	}
	if _u.mutation.InvitationCodeCleared() {
		_spec.ClearField(group.FieldInvitationCode, field.TypeString)
	}
	if value, ok := _u.mutation.RequireConfirmationDefault(); ok {
		_spec.SetField(group.FieldRequireConfirmationDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AutoCompleteRedemptionDefault(); ok {
		_spec.SetField(group.FieldAutoCompleteRedemptionDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AutoFulfillRedemptionDefault(); ok {
		_spec.SetField(group.FieldAutoFulfillRedemptionDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ProviderIncentiveRatio(); ok {
		_spec.SetField(group.FieldProviderIncentiveRatio, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProviderIncentiveRatio(); ok {
		_spec.AddField(group.FieldProviderIncentiveRatio, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(group.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.MembersTable,
			Columns: []string{group.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupmember.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.MembersTable,
			Columns: []string{group.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupmember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.MembersTable,
			Columns: []string{group.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupmember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AgreementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.AgreementsTable,
			Columns: []string{group.AgreementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agreement.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAgreementsIDs(); len(nodes) > 0 && !_u.mutation.AgreementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.AgreementsTable,
			Columns: []string{group.AgreementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agreement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgreementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.AgreementsTable,
			Columns: []string{group.AgreementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agreement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RewardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.RewardsTable,
			Columns: []string{group.RewardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reward.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRewardsIDs(); len(nodes) > 0 && !_u.mutation.RewardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.RewardsTable,
			Columns: []string{group.RewardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reward.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RewardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.RewardsTable,
			Columns: []string{group.RewardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reward.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PointLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.PointLogsTable,
			Columns: []string{group.PointLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pointlog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPointLogsIDs(); len(nodes) > 0 && !_u.mutation.PointLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.PointLogsTable,
			Columns: []string{group.PointLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pointlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PointLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.PointLogsTable,
			Columns: []string{group.PointLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pointlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MemberSummariesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.MemberSummariesTable,
			Columns: []string{group.MemberSummariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membersummary.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMemberSummariesIDs(); len(nodes) > 0 && !_u.mutation.MemberSummariesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.MemberSummariesTable,
			Columns: []string{group.MemberSummariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membersummary.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberSummariesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.MemberSummariesTable,
			Columns: []string{group.MemberSummariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membersummary.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Group{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{group.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
