// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/way2we/way2we_api/ent/agreement"
	"github.com/way2we/way2we_api/ent/group"
	"github.com/way2we/way2we_api/ent/groupmember"
	"github.com/way2we/way2we_api/ent/membersummary"
	"github.com/way2we/way2we_api/ent/pointlog"
	"github.com/way2we/way2we_api/ent/reward"
)

// GroupCreate is the builder for creating a Group entity.
type GroupCreate struct {
	config
	mutation *GroupMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *GroupCreate) SetName(v string) *GroupCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *GroupCreate) SetDescription(v string) *GroupCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *GroupCreate) SetNillableDescription(v *string) *GroupCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetInvitationCode sets the "invitation_code" field.
func (_c *GroupCreate) SetInvitationCode(v string) *GroupCreate {
	_c.mutation.SetInvitationCode(v)
	return _c
}

// SetNillableInvitationCode sets the "invitation_code" field if the given value is not nil.
func (_c *GroupCreate) SetNillableInvitationCode(v *string) *GroupCreate {
	if v != nil {
		_c.SetInvitationCode(*v)
	}
	return _c
}

// SetRequireConfirmationDefault sets the "require_confirmation_default" field.
func (_c *GroupCreate) SetRequireConfirmationDefault(v bool) *GroupCreate {
	_c.mutation.SetRequireConfirmationDefault(v)
	return _c
}

// SetNillableRequireConfirmationDefault sets the "require_confirmation_default" field if the given value is not nil.
func (_c *GroupCreate) SetNillableRequireConfirmationDefault(v *bool) *GroupCreate {
	if v != nil {
		_c.SetRequireConfirmationDefault(*v)
	}
	return _c
}

// SetAutoCompleteRedemptionDefault sets the "auto_complete_redemption_default" field.
func (_c *GroupCreate) SetAutoCompleteRedemptionDefault(v bool) *GroupCreate {
	_c.mutation.SetAutoCompleteRedemptionDefault(v)
	return _c
}

// SetNillableAutoCompleteRedemptionDefault sets the "auto_complete_redemption_default" field if the given value is not nil.
func (_c *GroupCreate) SetNillableAutoCompleteRedemptionDefault(v *bool) *GroupCreate {
	if v != nil {
		_c.SetAutoCompleteRedemptionDefault(*v)
	}
	return _c
}

// SetAutoFulfillRedemptionDefault sets the "auto_fulfill_redemption_default" field.
func (_c *GroupCreate) SetAutoFulfillRedemptionDefault(v bool) *GroupCreate {
	_c.mutation.SetAutoFulfillRedemptionDefault(v)
	return _c
}

// SetNillableAutoFulfillRedemptionDefault sets the "auto_fulfill_redemption_default" field if the given value is not nil.
func (_c *GroupCreate) SetNillableAutoFulfillRedemptionDefault(v *bool) *GroupCreate {
	if v != nil {
		_c.SetAutoFulfillRedemptionDefault(*v)
	}
	return _c
}

// SetProviderIncentiveRatio sets the "provider_incentive_ratio" field.
func (_c *GroupCreate) SetProviderIncentiveRatio(v int) *GroupCreate {
	_c.mutation.SetProviderIncentiveRatio(v)
	return _c
}

// SetNillableProviderIncentiveRatio sets the "provider_incentive_ratio" field if the given value is not nil.
func (_c *GroupCreate) SetNillableProviderIncentiveRatio(v *int) *GroupCreate {
	if v != nil {
		_c.SetProviderIncentiveRatio(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GroupCreate) SetCreatedAt(v time.Time) *GroupCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GroupCreate) SetNillableCreatedAt(v *time.Time) *GroupCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GroupCreate) SetUpdatedAt(v time.Time) *GroupCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GroupCreate) SetNillableUpdatedAt(v *time.Time) *GroupCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddMemberIDs adds the "members" edge to the GroupMember entity by IDs.
func (_c *GroupCreate) AddMemberIDs(ids ...int) *GroupCreate {
	_c.mutation.AddMemberIDs(ids...)
	return _c
}

// AddMembers adds the "members" edges to the GroupMember entity.
func (_c *GroupCreate) AddMembers(v ...*GroupMember) *GroupCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMemberIDs(ids...)
}

// AddAgreementIDs adds the "agreements" edge to the Agreement entity by IDs.
func (_c *GroupCreate) AddAgreementIDs(ids ...int) *GroupCreate {
	_c.mutation.AddAgreementIDs(ids...)
	return _c
}

// AddAgreements adds the "agreements" edges to the Agreement entity.
func (_c *GroupCreate) AddAgreements(v ...*Agreement) *GroupCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAgreementIDs(ids...)
}

// AddRewardIDs adds the "rewards" edge to the Reward entity by IDs.
func (_c *GroupCreate) AddRewardIDs(ids ...int) *GroupCreate {
	_c.mutation.AddRewardIDs(ids...)
	return _c
}

// AddRewards adds the "rewards" edges to the Reward entity.
func (_c *GroupCreate) AddRewards(v ...*Reward) *GroupCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRewardIDs(ids...)
}

// AddPointLogIDs adds the "point_logs" edge to the PointLog entity by IDs.
func (_c *GroupCreate) AddPointLogIDs(ids ...int) *GroupCreate {
	_c.mutation.AddPointLogIDs(ids...)
	return _c
}

// AddPointLogs adds the "point_logs" edges to the PointLog entity.
func (_c *GroupCreate) AddPointLogs(v ...*PointLog) *GroupCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPointLogIDs(ids...)
}

// AddMemberSummaryIDs adds the "member_summaries" edge to the MemberSummary entity by IDs.
func (_c *GroupCreate) AddMemberSummaryIDs(ids ...int) *GroupCreate {
	_c.mutation.AddMemberSummaryIDs(ids...)
	return _c
}

// AddMemberSummaries adds the "member_summaries" edges to the MemberSummary entity.
func (_c *GroupCreate) AddMemberSummaries(v ...*MemberSummary) *GroupCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMemberSummaryIDs(ids...)
}

// Mutation returns the GroupMutation object of the builder.
func (_c *GroupCreate) Mutation() *GroupMutation {
	return _c.mutation
}

// Save creates the Group in the database.
func (_c *GroupCreate) Save(ctx context.Context) (*Group, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroupCreate) SaveX(ctx context.Context) *Group {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GroupCreate) defaults() {
	if _, ok := _c.mutation.RequireConfirmationDefault(); !ok {
		v := group.DefaultRequireConfirmationDefault
		_c.mutation.SetRequireConfirmationDefault(v)
	}
	if _, ok := _c.mutation.AutoCompleteRedemptionDefault(); !ok {
		v := group.DefaultAutoCompleteRedemptionDefault
		_c.mutation.SetAutoCompleteRedemptionDefault(v)
	}
	if _, ok := _c.mutation.AutoFulfillRedemptionDefault(); !ok {
		v := group.DefaultAutoFulfillRedemptionDefault
		_c.mutation.SetAutoFulfillRedemptionDefault(v)
	}
	if _, ok := _c.mutation.ProviderIncentiveRatio(); !ok {
		v := group.DefaultProviderIncentiveRatio
		_c.mutation.SetProviderIncentiveRatio(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := group.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := group.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroupCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Group.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := group.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Group.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := group.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Group.description": %w`, err)}
		}
	}
	if v, ok := _c.mutation.InvitationCode(); ok {
		if err := group.InvitationCodeValidator(v); err != nil {
			return &ValidationError{Name: "invitation_code", err: fmt.Errorf(`ent: validator failed for field "Group.invitation_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequireConfirmationDefault(); !ok {
		return &ValidationError{Name: "require_confirmation_default", err: errors.New(`ent: missing required field "Group.require_confirmation_default"`)}
	}
	if _, ok := _c.mutation.AutoCompleteRedemptionDefault(); !ok {
		return &ValidationError{Name: "auto_complete_redemption_default", err: errors.New(`ent: missing required field "Group.auto_complete_redemption_default"`)}
	}
	if _, ok := _c.mutation.AutoFulfillRedemptionDefault(); !ok {
		return &ValidationError{Name: "auto_fulfill_redemption_default", err: errors.New(`ent: missing required field "Group.auto_fulfill_redemption_default"`)}
	}
	if _, ok := _c.mutation.ProviderIncentiveRatio(); !ok {
		return &ValidationError{Name: "provider_incentive_ratio", err: errors.New(`ent: missing required field "Group.provider_incentive_ratio"`)}
	}
	if v, ok := _c.mutation.ProviderIncentiveRatio(); ok {
		if err := group.ProviderIncentiveRatioValidator(v); err != nil {
			return &ValidationError{Name: "provider_incentive_ratio", err: fmt.Errorf(`ent: validator failed for field "Group.provider_incentive_ratio": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Group.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Group.updated_at"`)}
	}
	return nil
}

func (_c *GroupCreate) sqlSave(ctx context.Context) (*Group, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GroupCreate) createSpec() (*Group, *sqlgraph.CreateSpec) {
	var (
		_node = &Group{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(group.Table, sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(group.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(group.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.InvitationCode(); ok {
		_spec.SetField(group.FieldInvitationCode, field.TypeString, value)
		_node.InvitationCode = &value
	}
	if value, ok := _c.mutation.RequireConfirmationDefault(); ok {
		_spec.SetField(group.FieldRequireConfirmationDefault, field.TypeBool, value)
		_node.RequireConfirmationDefault = value
	}
	if value, ok := _c.mutation.AutoCompleteRedemptionDefault(); ok {
		_spec.SetField(group.FieldAutoCompleteRedemptionDefault, field.TypeBool, value)
		_node.AutoCompleteRedemptionDefault = value
	}
	if value, ok := _c.mutation.AutoFulfillRedemptionDefault(); ok {
		_spec.SetField(group.FieldAutoFulfillRedemptionDefault, field.TypeBool, value)
		_node.AutoFulfillRedemptionDefault = value
	}
	if value, ok := _c.mutation.ProviderIncentiveRatio(); ok {
		_spec.SetField(group.FieldProviderIncentiveRatio, field.TypeInt, value)
		_node.ProviderIncentiveRatio = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(group.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(group.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.MembersTable,
			Columns: []string{group.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupmember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AgreementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.AgreementsTable,
			Columns: []string{group.AgreementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agreement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RewardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.RewardsTable,
			Columns: []string{group.RewardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reward.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PointLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.PointLogsTable,
			Columns: []string{group.PointLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pointlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MemberSummariesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   group.MemberSummariesTable,
			Columns: []string{group.MemberSummariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membersummary.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GroupCreateBulk is the builder for creating many Group entities in bulk.
type GroupCreateBulk struct {
	config
	err      error
	builders []*GroupCreate
}

// Save creates the Group entities in the database.
func (_c *GroupCreateBulk) Save(ctx context.Context) ([]*Group, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Group, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroupCreateBulk) SaveX(ctx context.Context) []*Group {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
