// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/way2we/way2we_api/ent/group"
	"github.com/way2we/way2we_api/ent/membersummary"
	"github.com/way2we/way2we_api/ent/predicate"
	"github.com/way2we/way2we_api/ent/user"
)

// MemberSummaryUpdate is the builder for updating MemberSummary entities.
type MemberSummaryUpdate struct {
	config
	hooks    []Hook
	mutation *MemberSummaryMutation
}

// Where appends a list predicates to the MemberSummaryUpdate builder.
func (_u *MemberSummaryUpdate) Where(ps ...predicate.MemberSummary) *MemberSummaryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *MemberSummaryUpdate) SetGroupID(v int) *MemberSummaryUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *MemberSummaryUpdate) SetNillableGroupID(v *int) *MemberSummaryUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MemberSummaryUpdate) SetUserID(v int) *MemberSummaryUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MemberSummaryUpdate) SetNillableUserID(v *int) *MemberSummaryUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetBalance sets the "balance" field.
func (_u *MemberSummaryUpdate) SetBalance(v int) *MemberSummaryUpdate {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *MemberSummaryUpdate) SetNillableBalance(v *int) *MemberSummaryUpdate {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *MemberSummaryUpdate) AddBalance(v int) *MemberSummaryUpdate {
	_u.mutation.AddBalance(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MemberSummaryUpdate) SetUpdatedAt(v time.Time) *MemberSummaryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *MemberSummaryUpdate) SetGroup(v *Group) *MemberSummaryUpdate {
	return _u.SetGroupID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *MemberSummaryUpdate) SetUser(v *User) *MemberSummaryUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the MemberSummaryMutation object of the builder.
func (_u *MemberSummaryUpdate) Mutation() *MemberSummaryMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *MemberSummaryUpdate) ClearGroup() *MemberSummaryUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *MemberSummaryUpdate) ClearUser() *MemberSummaryUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MemberSummaryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemberSummaryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MemberSummaryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemberSummaryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MemberSummaryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := membersummary.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemberSummaryUpdate) check() error {
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MemberSummary.group"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MemberSummary.user"`)
	}
	return nil
}

func (_u *MemberSummaryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(membersummary.Table, membersummary.Columns, sqlgraph.NewFieldSpec(membersummary.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(membersummary.FieldBalance, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(membersummary.FieldBalance, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(membersummary.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   membersummary.GroupTable,
			Columns: []string{membersummary.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   membersummary.GroupTable,
			Columns: []string{membersummary.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   membersummary.UserTable,
			Columns: []string{membersummary.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   membersummary.UserTable,
			Columns: []string{membersummary.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{membersummary.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MemberSummaryUpdateOne is the builder for updating a single MemberSummary entity.
type MemberSummaryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MemberSummaryMutation
}

// SetGroupID sets the "group_id" field.
func (_u *MemberSummaryUpdateOne) SetGroupID(v int) *MemberSummaryUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *MemberSummaryUpdateOne) SetNillableGroupID(v *int) *MemberSummaryUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MemberSummaryUpdateOne) SetUserID(v int) *MemberSummaryUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MemberSummaryUpdateOne) SetNillableUserID(v *int) *MemberSummaryUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetBalance sets the "balance" field.
func (_u *MemberSummaryUpdateOne) SetBalance(v int) *MemberSummaryUpdateOne {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *MemberSummaryUpdateOne) SetNillableBalance(v *int) *MemberSummaryUpdateOne {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *MemberSummaryUpdateOne) AddBalance(v int) *MemberSummaryUpdateOne {
	_u.mutation.AddBalance(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MemberSummaryUpdateOne) SetUpdatedAt(v time.Time) *MemberSummaryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *MemberSummaryUpdateOne) SetGroup(v *Group) *MemberSummaryUpdateOne {
	return _u.SetGroupID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *MemberSummaryUpdateOne) SetUser(v *User) *MemberSummaryUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the MemberSummaryMutation object of the builder.
func (_u *MemberSummaryUpdateOne) Mutation() *MemberSummaryMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *MemberSummaryUpdateOne) ClearGroup() *MemberSummaryUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *MemberSummaryUpdateOne) ClearUser() *MemberSummaryUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the MemberSummaryUpdate builder.
func (_u *MemberSummaryUpdateOne) Where(ps ...predicate.MemberSummary) *MemberSummaryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MemberSummaryUpdateOne) Select(field string, fields ...string) *MemberSummaryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MemberSummary entity.
func (_u *MemberSummaryUpdateOne) Save(ctx context.Context) (*MemberSummary, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemberSummaryUpdateOne) SaveX(ctx context.Context) *MemberSummary {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MemberSummaryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemberSummaryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MemberSummaryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := membersummary.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemberSummaryUpdateOne) check() error {
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MemberSummary.group"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MemberSummary.user"`)
	}
	return nil
}

func (_u *MemberSummaryUpdateOne) sqlSave(ctx context.Context) (_node *MemberSummary, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(membersummary.Table, membersummary.Columns, sqlgraph.NewFieldSpec(membersummary.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MemberSummary.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, membersummary.FieldID)
		for _, f := range fields {
			if !membersummary.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != membersummary.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(membersummary.FieldBalance, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(membersummary.FieldBalance, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(membersummary.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   membersummary.GroupTable,
			Columns: []string{membersummary.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   membersummary.GroupTable,
			Columns: []string{membersummary.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   membersummary.UserTable,
			Columns: []string{membersummary.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   membersummary.UserTable,
			Columns: []string{membersummary.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MemberSummary{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{membersummary.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
