// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/way2we/way2we_api/ent/group"
	"github.com/way2we/way2we_api/ent/membersummary"
	"github.com/way2we/way2we_api/ent/user"
)

// MemberSummary is the model entity for the MemberSummary schema.
type MemberSummary struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Foreign key to Group
	GroupID int `json:"group_id,omitempty"`
	// Foreign key to User
	UserID int `json:"user_id,omitempty"`
	// Current points balance
	Balance int `json:"balance,omitempty"`
	// Last balance update timestamp
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MemberSummaryQuery when eager-loading is set.
	Edges        MemberSummaryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MemberSummaryEdges holds the relations/edges for other nodes in the graph.
type MemberSummaryEdges struct {
	// The group of this summary
	Group *Group `json:"group,omitempty"`
	// The user of this summary
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MemberSummaryEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MemberSummaryEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MemberSummary) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case membersummary.FieldID, membersummary.FieldGroupID, membersummary.FieldUserID, membersummary.FieldBalance:
			values[i] = new(sql.NullInt64)
		case membersummary.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MemberSummary fields.
func (_m *MemberSummary) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case membersummary.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case membersummary.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = int(value.Int64)
			}
		case membersummary.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case membersummary.FieldBalance:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field balance", values[i])
			} else if value.Valid {
				_m.Balance = int(value.Int64)
			}
		case membersummary.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MemberSummary.
// This includes values selected through modifiers, order, etc.
func (_m *MemberSummary) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the MemberSummary entity.
func (_m *MemberSummary) QueryGroup() *GroupQuery {
	return NewMemberSummaryClient(_m.config).QueryGroup(_m)
}

// QueryUser queries the "user" edge of the MemberSummary entity.
func (_m *MemberSummary) QueryUser() *UserQuery {
	return NewMemberSummaryClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this MemberSummary.
// Note that you need to call MemberSummary.Unwrap() before calling this method if this MemberSummary
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MemberSummary) Update() *MemberSummaryUpdateOne {
	return NewMemberSummaryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MemberSummary entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MemberSummary) Unwrap() *MemberSummary {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MemberSummary is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MemberSummary) String() string {
	var builder strings.Builder
	builder.WriteString("MemberSummary(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("balance=")
	builder.WriteString(fmt.Sprintf("%v", _m.Balance))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MemberSummaries is a parsable slice of MemberSummary.
type MemberSummaries []*MemberSummary
