// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/way2we/way2we_api/ent/group"
	"github.com/way2we/way2we_api/ent/redemptionorder"
	"github.com/way2we/way2we_api/ent/reward"
	"github.com/way2we/way2we_api/ent/user"
)

// RedemptionOrder is the model entity for the RedemptionOrder schema.
type RedemptionOrder struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Foreign key to Group
	GroupID int `json:"group_id,omitempty"`
	// Foreign key to Reward
	RewardID int `json:"reward_id,omitempty"`
	// User who created the order
	ConsumerID int `json:"consumer_id,omitempty"`
	// Snapshot of reward provider_id
	ProviderID int `json:"provider_id,omitempty"`
	// Order quantity, minimum 1
	Quantity int `json:"quantity,omitempty"`
	// Snapshot of reward cost_points
	UnitCostPoints int `json:"unit_cost_points,omitempty"`
	// Total points cost (unit * quantity)
	TotalCostPoints int `json:"total_cost_points,omitempty"`
	// Order status
	Status redemptionorder.Status `json:"status,omitempty"`
	// Snapshot of reward auto_fulfill
	AutoFulfill bool `json:"auto_fulfill,omitempty"`
	// Snapshot of reward auto_complete
	AutoComplete bool `json:"auto_complete,omitempty"`
	// Snapshot of group provider incentive ratio (0-100)
	ProviderIncentiveRatio int `json:"provider_incentive_ratio,omitempty"`
	// Fulfillment timestamp
	FulfilledAt *time.Time `json:"fulfilled_at,omitempty"`
	// Confirmation timestamp
	ConfirmedAt *time.Time `json:"confirmed_at,omitempty"`
	// Unsatisfied end timestamp
	EndedAt *time.Time `json:"ended_at,omitempty"`
	// Optional unsatisfied reason (max 200 chars)
	UnsatisfiedReason string `json:"unsatisfied_reason,omitempty"`
	// Order creation timestamp
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Order update timestamp
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RedemptionOrderQuery when eager-loading is set.
	Edges        RedemptionOrderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RedemptionOrderEdges holds the relations/edges for other nodes in the graph.
type RedemptionOrderEdges struct {
	// The group this order belongs to
	Group *Group `json:"group,omitempty"`
	// The reward this order is for
	Reward *Reward `json:"reward,omitempty"`
	// The user who created the order
	Consumer *User `json:"consumer,omitempty"`
	// The user who provides the reward
	Provider *User `json:"provider,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RedemptionOrderEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// RewardOrErr returns the Reward value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RedemptionOrderEdges) RewardOrErr() (*Reward, error) {
	if e.Reward != nil {
		return e.Reward, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: reward.Label}
	}
	return nil, &NotLoadedError{edge: "reward"}
}

// ConsumerOrErr returns the Consumer value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RedemptionOrderEdges) ConsumerOrErr() (*User, error) {
	if e.Consumer != nil {
		return e.Consumer, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "consumer"}
}

// ProviderOrErr returns the Provider value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RedemptionOrderEdges) ProviderOrErr() (*User, error) {
	if e.Provider != nil {
		return e.Provider, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "provider"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RedemptionOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case redemptionorder.FieldAutoFulfill, redemptionorder.FieldAutoComplete:
			values[i] = new(sql.NullBool)
		case redemptionorder.FieldID, redemptionorder.FieldGroupID, redemptionorder.FieldRewardID, redemptionorder.FieldConsumerID, redemptionorder.FieldProviderID, redemptionorder.FieldQuantity, redemptionorder.FieldUnitCostPoints, redemptionorder.FieldTotalCostPoints, redemptionorder.FieldProviderIncentiveRatio:
			values[i] = new(sql.NullInt64)
		case redemptionorder.FieldStatus, redemptionorder.FieldUnsatisfiedReason:
			values[i] = new(sql.NullString)
		case redemptionorder.FieldFulfilledAt, redemptionorder.FieldConfirmedAt, redemptionorder.FieldEndedAt, redemptionorder.FieldCreatedAt, redemptionorder.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RedemptionOrder fields.
func (_m *RedemptionOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case redemptionorder.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case redemptionorder.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = int(value.Int64)
			}
		case redemptionorder.FieldRewardID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reward_id", values[i])
			} else if value.Valid {
				_m.RewardID = int(value.Int64)
			}
		case redemptionorder.FieldConsumerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field consumer_id", values[i])
			} else if value.Valid {
				_m.ConsumerID = int(value.Int64)
			}
		case redemptionorder.FieldProviderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field provider_id", values[i])
			} else if value.Valid {
				_m.ProviderID = int(value.Int64)
			}
		case redemptionorder.FieldQuantity:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				_m.Quantity = int(value.Int64)
			}
		case redemptionorder.FieldUnitCostPoints:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field unit_cost_points", values[i])
			} else if value.Valid {
				_m.UnitCostPoints = int(value.Int64)
			}
		case redemptionorder.FieldTotalCostPoints:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_cost_points", values[i])
			} else if value.Valid {
				_m.TotalCostPoints = int(value.Int64)
			}
		case redemptionorder.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = redemptionorder.Status(value.String)
			}
		case redemptionorder.FieldAutoFulfill:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field auto_fulfill", values[i])
			} else if value.Valid {
				_m.AutoFulfill = value.Bool
			}
		case redemptionorder.FieldAutoComplete:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field auto_complete", values[i])
			} else if value.Valid {
				_m.AutoComplete = value.Bool
			}
		case redemptionorder.FieldProviderIncentiveRatio:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field provider_incentive_ratio", values[i])
			} else if value.Valid {
				_m.ProviderIncentiveRatio = int(value.Int64)
			}
		case redemptionorder.FieldFulfilledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field fulfilled_at", values[i])
			} else if value.Valid {
				_m.FulfilledAt = new(time.Time)
				*_m.FulfilledAt = value.Time
			}
		case redemptionorder.FieldConfirmedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field confirmed_at", values[i])
			} else if value.Valid {
				_m.ConfirmedAt = new(time.Time)
				*_m.ConfirmedAt = value.Time
			}
		case redemptionorder.FieldEndedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ended_at", values[i])
			} else if value.Valid {
				_m.EndedAt = new(time.Time)
				*_m.EndedAt = value.Time
			}
		case redemptionorder.FieldUnsatisfiedReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field unsatisfied_reason", values[i])
			} else if value.Valid {
				_m.UnsatisfiedReason = value.String
			}
		case redemptionorder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case redemptionorder.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RedemptionOrder.
// This includes values selected through modifiers, order, etc.
func (_m *RedemptionOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the RedemptionOrder entity.
func (_m *RedemptionOrder) QueryGroup() *GroupQuery {
	return NewRedemptionOrderClient(_m.config).QueryGroup(_m)
}

// QueryReward queries the "reward" edge of the RedemptionOrder entity.
func (_m *RedemptionOrder) QueryReward() *RewardQuery {
	return NewRedemptionOrderClient(_m.config).QueryReward(_m)
}

// QueryConsumer queries the "consumer" edge of the RedemptionOrder entity.
func (_m *RedemptionOrder) QueryConsumer() *UserQuery {
	return NewRedemptionOrderClient(_m.config).QueryConsumer(_m)
}

// QueryProvider queries the "provider" edge of the RedemptionOrder entity.
func (_m *RedemptionOrder) QueryProvider() *UserQuery {
	return NewRedemptionOrderClient(_m.config).QueryProvider(_m)
}

// Update returns a builder for updating this RedemptionOrder.
// Note that you need to call RedemptionOrder.Unwrap() before calling this method if this RedemptionOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RedemptionOrder) Update() *RedemptionOrderUpdateOne {
	return NewRedemptionOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RedemptionOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RedemptionOrder) Unwrap() *RedemptionOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RedemptionOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RedemptionOrder) String() string {
	var builder strings.Builder
	builder.WriteString("RedemptionOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("reward_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RewardID))
	builder.WriteString(", ")
	builder.WriteString("consumer_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConsumerID))
	builder.WriteString(", ")
	builder.WriteString("provider_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderID))
	builder.WriteString(", ")
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quantity))
	builder.WriteString(", ")
	builder.WriteString("unit_cost_points=")
	builder.WriteString(fmt.Sprintf("%v", _m.UnitCostPoints))
	builder.WriteString(", ")
	builder.WriteString("total_cost_points=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalCostPoints))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("auto_fulfill=")
	builder.WriteString(fmt.Sprintf("%v", _m.AutoFulfill))
	builder.WriteString(", ")
	builder.WriteString("auto_complete=")
	builder.WriteString(fmt.Sprintf("%v", _m.AutoComplete))
	builder.WriteString(", ")
	builder.WriteString("provider_incentive_ratio=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderIncentiveRatio))
	builder.WriteString(", ")
	if v := _m.FulfilledAt; v != nil {
		builder.WriteString("fulfilled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ConfirmedAt; v != nil {
		builder.WriteString("confirmed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.EndedAt; v != nil {
		builder.WriteString("ended_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("unsatisfied_reason=")
	builder.WriteString(_m.UnsatisfiedReason)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RedemptionOrders is a parsable slice of RedemptionOrder.
type RedemptionOrders []*RedemptionOrder
