// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/way2we/way2we_api/ent/group"
	"github.com/way2we/way2we_api/ent/groupmember"
	"github.com/way2we/way2we_api/ent/schema"
	"github.com/way2we/way2we_api/ent/tokenblacklist"
	"github.com/way2we/way2we_api/ent/user"
	"github.com/way2we/way2we_api/ent/useridentity"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescName is the schema descriptor for name field.
	groupDescName := groupFields[0].Descriptor()
	// group.NameValidator is a validator for the "name" field. It is called by the builders before save.
	group.NameValidator = func() func(string) error {
		validators := groupDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// groupDescDescription is the schema descriptor for description field.
	groupDescDescription := groupFields[1].Descriptor()
	// group.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	group.DescriptionValidator = groupDescDescription.Validators[0].(func(string) error)
	// groupDescInvitationCode is the schema descriptor for invitation_code field.
	groupDescInvitationCode := groupFields[2].Descriptor()
	// group.InvitationCodeValidator is a validator for the "invitation_code" field. It is called by the builders before save.
	group.InvitationCodeValidator = groupDescInvitationCode.Validators[0].(func(string) error)
	// groupDescCreatedAt is the schema descriptor for created_at field.
	groupDescCreatedAt := groupFields[3].Descriptor()
	// group.DefaultCreatedAt holds the default value on creation for the created_at field.
	group.DefaultCreatedAt = groupDescCreatedAt.Default.(func() time.Time)
	// groupDescUpdatedAt is the schema descriptor for updated_at field.
	groupDescUpdatedAt := groupFields[4].Descriptor()
	// group.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	group.DefaultUpdatedAt = groupDescUpdatedAt.Default.(func() time.Time)
	// group.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	group.UpdateDefaultUpdatedAt = groupDescUpdatedAt.UpdateDefault.(func() time.Time)
	groupmemberFields := schema.GroupMember{}.Fields()
	_ = groupmemberFields
	// groupmemberDescJoinedAt is the schema descriptor for joined_at field.
	groupmemberDescJoinedAt := groupmemberFields[3].Descriptor()
	// groupmember.DefaultJoinedAt holds the default value on creation for the joined_at field.
	groupmember.DefaultJoinedAt = groupmemberDescJoinedAt.Default.(func() time.Time)
	tokenblacklistFields := schema.TokenBlacklist{}.Fields()
	_ = tokenblacklistFields
	// tokenblacklistDescTokenHash is the schema descriptor for token_hash field.
	tokenblacklistDescTokenHash := tokenblacklistFields[0].Descriptor()
	// tokenblacklist.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	tokenblacklist.TokenHashValidator = tokenblacklistDescTokenHash.Validators[0].(func(string) error)
	// tokenblacklistDescCreatedAt is the schema descriptor for created_at field.
	tokenblacklistDescCreatedAt := tokenblacklistFields[2].Descriptor()
	// tokenblacklist.DefaultCreatedAt holds the default value on creation for the created_at field.
	tokenblacklist.DefaultCreatedAt = tokenblacklistDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescNickname is the schema descriptor for nickname field.
	userDescNickname := userFields[0].Descriptor()
	// user.NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	user.NicknameValidator = userDescNickname.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	useridentityFields := schema.UserIdentity{}.Fields()
	_ = useridentityFields
	// useridentityDescIdentifier is the schema descriptor for identifier field.
	useridentityDescIdentifier := useridentityFields[1].Descriptor()
	// useridentity.IdentifierValidator is a validator for the "identifier" field. It is called by the builders before save.
	useridentity.IdentifierValidator = useridentityDescIdentifier.Validators[0].(func(string) error)
	// useridentityDescVerified is the schema descriptor for verified field.
	useridentityDescVerified := useridentityFields[2].Descriptor()
	// useridentity.DefaultVerified holds the default value on creation for the verified field.
	useridentity.DefaultVerified = useridentityDescVerified.Default.(bool)
	// useridentityDescCreatedAt is the schema descriptor for created_at field.
	useridentityDescCreatedAt := useridentityFields[3].Descriptor()
	// useridentity.DefaultCreatedAt holds the default value on creation for the created_at field.
	useridentity.DefaultCreatedAt = useridentityDescCreatedAt.Default.(func() time.Time)
	// useridentityDescUpdatedAt is the schema descriptor for updated_at field.
	useridentityDescUpdatedAt := useridentityFields[4].Descriptor()
	// useridentity.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	useridentity.DefaultUpdatedAt = useridentityDescUpdatedAt.Default.(func() time.Time)
	// useridentity.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	useridentity.UpdateDefaultUpdatedAt = useridentityDescUpdatedAt.UpdateDefault.(func() time.Time)
}
