// Code generated by ent, DO NOT EDIT.

package redemptionorder

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the redemptionorder type in the database.
	Label = "redemption_order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldRewardID holds the string denoting the reward_id field in the database.
	FieldRewardID = "reward_id"
	// FieldConsumerID holds the string denoting the consumer_id field in the database.
	FieldConsumerID = "consumer_id"
	// FieldProviderID holds the string denoting the provider_id field in the database.
	FieldProviderID = "provider_id"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// FieldUnitCostPoints holds the string denoting the unit_cost_points field in the database.
	FieldUnitCostPoints = "unit_cost_points"
	// FieldTotalCostPoints holds the string denoting the total_cost_points field in the database.
	FieldTotalCostPoints = "total_cost_points"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldAutoFulfill holds the string denoting the auto_fulfill field in the database.
	FieldAutoFulfill = "auto_fulfill"
	// FieldAutoComplete holds the string denoting the auto_complete field in the database.
	FieldAutoComplete = "auto_complete"
	// FieldProviderIncentiveRatio holds the string denoting the provider_incentive_ratio field in the database.
	FieldProviderIncentiveRatio = "provider_incentive_ratio"
	// FieldFulfilledAt holds the string denoting the fulfilled_at field in the database.
	FieldFulfilledAt = "fulfilled_at"
	// FieldConfirmedAt holds the string denoting the confirmed_at field in the database.
	FieldConfirmedAt = "confirmed_at"
	// FieldEndedAt holds the string denoting the ended_at field in the database.
	FieldEndedAt = "ended_at"
	// FieldUnsatisfiedReason holds the string denoting the unsatisfied_reason field in the database.
	FieldUnsatisfiedReason = "unsatisfied_reason"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// EdgeReward holds the string denoting the reward edge name in mutations.
	EdgeReward = "reward"
	// EdgeConsumer holds the string denoting the consumer edge name in mutations.
	EdgeConsumer = "consumer"
	// EdgeProvider holds the string denoting the provider edge name in mutations.
	EdgeProvider = "provider"
	// Table holds the table name of the redemptionorder in the database.
	Table = "redemption_orders"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "redemption_orders"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
	// RewardTable is the table that holds the reward relation/edge.
	RewardTable = "redemption_orders"
	// RewardInverseTable is the table name for the Reward entity.
	// It exists in this package in order to avoid circular dependency with the "reward" package.
	RewardInverseTable = "rewards"
	// RewardColumn is the table column denoting the reward relation/edge.
	RewardColumn = "reward_id"
	// ConsumerTable is the table that holds the consumer relation/edge.
	ConsumerTable = "redemption_orders"
	// ConsumerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ConsumerInverseTable = "users"
	// ConsumerColumn is the table column denoting the consumer relation/edge.
	ConsumerColumn = "consumer_id"
	// ProviderTable is the table that holds the provider relation/edge.
	ProviderTable = "redemption_orders"
	// ProviderInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ProviderInverseTable = "users"
	// ProviderColumn is the table column denoting the provider relation/edge.
	ProviderColumn = "provider_id"
)

// Columns holds all SQL columns for redemptionorder fields.
var Columns = []string{
	FieldID,
	FieldGroupID,
	FieldRewardID,
	FieldConsumerID,
	FieldProviderID,
	FieldQuantity,
	FieldUnitCostPoints,
	FieldTotalCostPoints,
	FieldStatus,
	FieldAutoFulfill,
	FieldAutoComplete,
	FieldProviderIncentiveRatio,
	FieldFulfilledAt,
	FieldConfirmedAt,
	FieldEndedAt,
	FieldUnsatisfiedReason,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	QuantityValidator func(int) error
	// UnitCostPointsValidator is a validator for the "unit_cost_points" field. It is called by the builders before save.
	UnitCostPointsValidator func(int) error
	// TotalCostPointsValidator is a validator for the "total_cost_points" field. It is called by the builders before save.
	TotalCostPointsValidator func(int) error
	// DefaultAutoFulfill holds the default value on creation for the "auto_fulfill" field.
	DefaultAutoFulfill bool
	// DefaultAutoComplete holds the default value on creation for the "auto_complete" field.
	DefaultAutoComplete bool
	// DefaultProviderIncentiveRatio holds the default value on creation for the "provider_incentive_ratio" field.
	DefaultProviderIncentiveRatio int
	// ProviderIncentiveRatioValidator is a validator for the "provider_incentive_ratio" field. It is called by the builders before save.
	ProviderIncentiveRatioValidator func(int) error
	// UnsatisfiedReasonValidator is a validator for the "unsatisfied_reason" field. It is called by the builders before save.
	UnsatisfiedReasonValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusAwaitingFulfill is the default value of the Status enum.
const DefaultStatus = StatusAwaitingFulfill

// Status values.
const (
	StatusAwaitingFulfill Status = "awaiting_fulfill"
	StatusAwaitingConfirm Status = "awaiting_confirm"
	StatusCompleted       Status = "completed"
	StatusUnsatisfied     Status = "unsatisfied"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusAwaitingFulfill, StatusAwaitingConfirm, StatusCompleted, StatusUnsatisfied:
		return nil
	default:
		return fmt.Errorf("redemptionorder: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the RedemptionOrder queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByRewardID orders the results by the reward_id field.
func ByRewardID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRewardID, opts...).ToFunc()
}

// ByConsumerID orders the results by the consumer_id field.
func ByConsumerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsumerID, opts...).ToFunc()
}

// ByProviderID orders the results by the provider_id field.
func ByProviderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderID, opts...).ToFunc()
}

// ByQuantity orders the results by the quantity field.
func ByQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantity, opts...).ToFunc()
}

// ByUnitCostPoints orders the results by the unit_cost_points field.
func ByUnitCostPoints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitCostPoints, opts...).ToFunc()
}

// ByTotalCostPoints orders the results by the total_cost_points field.
func ByTotalCostPoints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalCostPoints, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByAutoFulfill orders the results by the auto_fulfill field.
func ByAutoFulfill(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAutoFulfill, opts...).ToFunc()
}

// ByAutoComplete orders the results by the auto_complete field.
func ByAutoComplete(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAutoComplete, opts...).ToFunc()
}

// ByProviderIncentiveRatio orders the results by the provider_incentive_ratio field.
func ByProviderIncentiveRatio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderIncentiveRatio, opts...).ToFunc()
}

// ByFulfilledAt orders the results by the fulfilled_at field.
func ByFulfilledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFulfilledAt, opts...).ToFunc()
}

// ByConfirmedAt orders the results by the confirmed_at field.
func ByConfirmedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfirmedAt, opts...).ToFunc()
}

// ByEndedAt orders the results by the ended_at field.
func ByEndedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndedAt, opts...).ToFunc()
}

// ByUnsatisfiedReason orders the results by the unsatisfied_reason field.
func ByUnsatisfiedReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnsatisfiedReason, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByRewardField orders the results by reward field.
func ByRewardField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRewardStep(), sql.OrderByField(field, opts...))
	}
}

// ByConsumerField orders the results by consumer field.
func ByConsumerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newConsumerStep(), sql.OrderByField(field, opts...))
	}
}

// ByProviderField orders the results by provider field.
func ByProviderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProviderStep(), sql.OrderByField(field, opts...))
	}
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
	)
}
func newRewardStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RewardInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, RewardTable, RewardColumn),
	)
}
func newConsumerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ConsumerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ConsumerTable, ConsumerColumn),
	)
}
func newProviderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProviderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ProviderTable, ProviderColumn),
	)
}
