// Code generated by ent, DO NOT EDIT.

package redemptionorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/way2we/way2we_api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldLTE(FieldID, id))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldGroupID, v))
}

// RewardID applies equality check predicate on the "reward_id" field. It's identical to RewardIDEQ.
func RewardID(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldRewardID, v))
}

// ConsumerID applies equality check predicate on the "consumer_id" field. It's identical to ConsumerIDEQ.
func ConsumerID(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldConsumerID, v))
}

// ProviderID applies equality check predicate on the "provider_id" field. It's identical to ProviderIDEQ.
func ProviderID(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldProviderID, v))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldQuantity, v))
}

// UnitCostPoints applies equality check predicate on the "unit_cost_points" field. It's identical to UnitCostPointsEQ.
func UnitCostPoints(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldUnitCostPoints, v))
}

// TotalCostPoints applies equality check predicate on the "total_cost_points" field. It's identical to TotalCostPointsEQ.
func TotalCostPoints(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldTotalCostPoints, v))
}

// AutoFulfill applies equality check predicate on the "auto_fulfill" field. It's identical to AutoFulfillEQ.
func AutoFulfill(v bool) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldAutoFulfill, v))
}

// AutoComplete applies equality check predicate on the "auto_complete" field. It's identical to AutoCompleteEQ.
func AutoComplete(v bool) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldAutoComplete, v))
}

// ProviderIncentiveRatio applies equality check predicate on the "provider_incentive_ratio" field. It's identical to ProviderIncentiveRatioEQ.
func ProviderIncentiveRatio(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldProviderIncentiveRatio, v))
}

// FulfilledAt applies equality check predicate on the "fulfilled_at" field. It's identical to FulfilledAtEQ.
func FulfilledAt(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldFulfilledAt, v))
}

// ConfirmedAt applies equality check predicate on the "confirmed_at" field. It's identical to ConfirmedAtEQ.
func ConfirmedAt(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldConfirmedAt, v))
}

// EndedAt applies equality check predicate on the "ended_at" field. It's identical to EndedAtEQ.
func EndedAt(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldEndedAt, v))
}

// UnsatisfiedReason applies equality check predicate on the "unsatisfied_reason" field. It's identical to UnsatisfiedReasonEQ.
func UnsatisfiedReason(v string) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldUnsatisfiedReason, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNotIn(FieldGroupID, vs...))
}

// RewardIDEQ applies the EQ predicate on the "reward_id" field.
func RewardIDEQ(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldRewardID, v))
}

// RewardIDNEQ applies the NEQ predicate on the "reward_id" field.
func RewardIDNEQ(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNEQ(FieldRewardID, v))
}

// RewardIDIn applies the In predicate on the "reward_id" field.
func RewardIDIn(vs ...int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldIn(FieldRewardID, vs...))
}

// RewardIDNotIn applies the NotIn predicate on the "reward_id" field.
func RewardIDNotIn(vs ...int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNotIn(FieldRewardID, vs...))
}

// ConsumerIDEQ applies the EQ predicate on the "consumer_id" field.
func ConsumerIDEQ(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldConsumerID, v))
}

// ConsumerIDNEQ applies the NEQ predicate on the "consumer_id" field.
func ConsumerIDNEQ(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNEQ(FieldConsumerID, v))
}

// ConsumerIDIn applies the In predicate on the "consumer_id" field.
func ConsumerIDIn(vs ...int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldIn(FieldConsumerID, vs...))
}

// ConsumerIDNotIn applies the NotIn predicate on the "consumer_id" field.
func ConsumerIDNotIn(vs ...int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNotIn(FieldConsumerID, vs...))
}

// ProviderIDEQ applies the EQ predicate on the "provider_id" field.
func ProviderIDEQ(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldProviderID, v))
}

// ProviderIDNEQ applies the NEQ predicate on the "provider_id" field.
func ProviderIDNEQ(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNEQ(FieldProviderID, v))
}

// ProviderIDIn applies the In predicate on the "provider_id" field.
func ProviderIDIn(vs ...int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldIn(FieldProviderID, vs...))
}

// ProviderIDNotIn applies the NotIn predicate on the "provider_id" field.
func ProviderIDNotIn(vs ...int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNotIn(FieldProviderID, vs...))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldLTE(FieldQuantity, v))
}

// UnitCostPointsEQ applies the EQ predicate on the "unit_cost_points" field.
func UnitCostPointsEQ(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldUnitCostPoints, v))
}

// UnitCostPointsNEQ applies the NEQ predicate on the "unit_cost_points" field.
func UnitCostPointsNEQ(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNEQ(FieldUnitCostPoints, v))
}

// UnitCostPointsIn applies the In predicate on the "unit_cost_points" field.
func UnitCostPointsIn(vs ...int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldIn(FieldUnitCostPoints, vs...))
}

// UnitCostPointsNotIn applies the NotIn predicate on the "unit_cost_points" field.
func UnitCostPointsNotIn(vs ...int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNotIn(FieldUnitCostPoints, vs...))
}

// UnitCostPointsGT applies the GT predicate on the "unit_cost_points" field.
func UnitCostPointsGT(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldGT(FieldUnitCostPoints, v))
}

// UnitCostPointsGTE applies the GTE predicate on the "unit_cost_points" field.
func UnitCostPointsGTE(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldGTE(FieldUnitCostPoints, v))
}

// UnitCostPointsLT applies the LT predicate on the "unit_cost_points" field.
func UnitCostPointsLT(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldLT(FieldUnitCostPoints, v))
}

// UnitCostPointsLTE applies the LTE predicate on the "unit_cost_points" field.
func UnitCostPointsLTE(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldLTE(FieldUnitCostPoints, v))
}

// TotalCostPointsEQ applies the EQ predicate on the "total_cost_points" field.
func TotalCostPointsEQ(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldTotalCostPoints, v))
}

// TotalCostPointsNEQ applies the NEQ predicate on the "total_cost_points" field.
func TotalCostPointsNEQ(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNEQ(FieldTotalCostPoints, v))
}

// TotalCostPointsIn applies the In predicate on the "total_cost_points" field.
func TotalCostPointsIn(vs ...int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldIn(FieldTotalCostPoints, vs...))
}

// TotalCostPointsNotIn applies the NotIn predicate on the "total_cost_points" field.
func TotalCostPointsNotIn(vs ...int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNotIn(FieldTotalCostPoints, vs...))
}

// TotalCostPointsGT applies the GT predicate on the "total_cost_points" field.
func TotalCostPointsGT(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldGT(FieldTotalCostPoints, v))
}

// TotalCostPointsGTE applies the GTE predicate on the "total_cost_points" field.
func TotalCostPointsGTE(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldGTE(FieldTotalCostPoints, v))
}

// TotalCostPointsLT applies the LT predicate on the "total_cost_points" field.
func TotalCostPointsLT(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldLT(FieldTotalCostPoints, v))
}

// TotalCostPointsLTE applies the LTE predicate on the "total_cost_points" field.
func TotalCostPointsLTE(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldLTE(FieldTotalCostPoints, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNotIn(FieldStatus, vs...))
}

// AutoFulfillEQ applies the EQ predicate on the "auto_fulfill" field.
func AutoFulfillEQ(v bool) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldAutoFulfill, v))
}

// AutoFulfillNEQ applies the NEQ predicate on the "auto_fulfill" field.
func AutoFulfillNEQ(v bool) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNEQ(FieldAutoFulfill, v))
}

// AutoCompleteEQ applies the EQ predicate on the "auto_complete" field.
func AutoCompleteEQ(v bool) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldAutoComplete, v))
}

// AutoCompleteNEQ applies the NEQ predicate on the "auto_complete" field.
func AutoCompleteNEQ(v bool) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNEQ(FieldAutoComplete, v))
}

// ProviderIncentiveRatioEQ applies the EQ predicate on the "provider_incentive_ratio" field.
func ProviderIncentiveRatioEQ(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldProviderIncentiveRatio, v))
}

// ProviderIncentiveRatioNEQ applies the NEQ predicate on the "provider_incentive_ratio" field.
func ProviderIncentiveRatioNEQ(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNEQ(FieldProviderIncentiveRatio, v))
}

// ProviderIncentiveRatioIn applies the In predicate on the "provider_incentive_ratio" field.
func ProviderIncentiveRatioIn(vs ...int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldIn(FieldProviderIncentiveRatio, vs...))
}

// ProviderIncentiveRatioNotIn applies the NotIn predicate on the "provider_incentive_ratio" field.
func ProviderIncentiveRatioNotIn(vs ...int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNotIn(FieldProviderIncentiveRatio, vs...))
}

// ProviderIncentiveRatioGT applies the GT predicate on the "provider_incentive_ratio" field.
func ProviderIncentiveRatioGT(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldGT(FieldProviderIncentiveRatio, v))
}

// ProviderIncentiveRatioGTE applies the GTE predicate on the "provider_incentive_ratio" field.
func ProviderIncentiveRatioGTE(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldGTE(FieldProviderIncentiveRatio, v))
}

// ProviderIncentiveRatioLT applies the LT predicate on the "provider_incentive_ratio" field.
func ProviderIncentiveRatioLT(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldLT(FieldProviderIncentiveRatio, v))
}

// ProviderIncentiveRatioLTE applies the LTE predicate on the "provider_incentive_ratio" field.
func ProviderIncentiveRatioLTE(v int) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldLTE(FieldProviderIncentiveRatio, v))
}

// FulfilledAtEQ applies the EQ predicate on the "fulfilled_at" field.
func FulfilledAtEQ(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldFulfilledAt, v))
}

// FulfilledAtNEQ applies the NEQ predicate on the "fulfilled_at" field.
func FulfilledAtNEQ(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNEQ(FieldFulfilledAt, v))
}

// FulfilledAtIn applies the In predicate on the "fulfilled_at" field.
func FulfilledAtIn(vs ...time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldIn(FieldFulfilledAt, vs...))
}

// FulfilledAtNotIn applies the NotIn predicate on the "fulfilled_at" field.
func FulfilledAtNotIn(vs ...time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNotIn(FieldFulfilledAt, vs...))
}

// FulfilledAtGT applies the GT predicate on the "fulfilled_at" field.
func FulfilledAtGT(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldGT(FieldFulfilledAt, v))
}

// FulfilledAtGTE applies the GTE predicate on the "fulfilled_at" field.
func FulfilledAtGTE(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldGTE(FieldFulfilledAt, v))
}

// FulfilledAtLT applies the LT predicate on the "fulfilled_at" field.
func FulfilledAtLT(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldLT(FieldFulfilledAt, v))
}

// FulfilledAtLTE applies the LTE predicate on the "fulfilled_at" field.
func FulfilledAtLTE(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldLTE(FieldFulfilledAt, v))
}

// FulfilledAtIsNil applies the IsNil predicate on the "fulfilled_at" field.
func FulfilledAtIsNil() predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldIsNull(FieldFulfilledAt))
}

// FulfilledAtNotNil applies the NotNil predicate on the "fulfilled_at" field.
func FulfilledAtNotNil() predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNotNull(FieldFulfilledAt))
}

// ConfirmedAtEQ applies the EQ predicate on the "confirmed_at" field.
func ConfirmedAtEQ(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldConfirmedAt, v))
}

// ConfirmedAtNEQ applies the NEQ predicate on the "confirmed_at" field.
func ConfirmedAtNEQ(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNEQ(FieldConfirmedAt, v))
}

// ConfirmedAtIn applies the In predicate on the "confirmed_at" field.
func ConfirmedAtIn(vs ...time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldIn(FieldConfirmedAt, vs...))
}

// ConfirmedAtNotIn applies the NotIn predicate on the "confirmed_at" field.
func ConfirmedAtNotIn(vs ...time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNotIn(FieldConfirmedAt, vs...))
}

// ConfirmedAtGT applies the GT predicate on the "confirmed_at" field.
func ConfirmedAtGT(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldGT(FieldConfirmedAt, v))
}

// ConfirmedAtGTE applies the GTE predicate on the "confirmed_at" field.
func ConfirmedAtGTE(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldGTE(FieldConfirmedAt, v))
}

// ConfirmedAtLT applies the LT predicate on the "confirmed_at" field.
func ConfirmedAtLT(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldLT(FieldConfirmedAt, v))
}

// ConfirmedAtLTE applies the LTE predicate on the "confirmed_at" field.
func ConfirmedAtLTE(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldLTE(FieldConfirmedAt, v))
}

// ConfirmedAtIsNil applies the IsNil predicate on the "confirmed_at" field.
func ConfirmedAtIsNil() predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldIsNull(FieldConfirmedAt))
}

// ConfirmedAtNotNil applies the NotNil predicate on the "confirmed_at" field.
func ConfirmedAtNotNil() predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNotNull(FieldConfirmedAt))
}

// EndedAtEQ applies the EQ predicate on the "ended_at" field.
func EndedAtEQ(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldEndedAt, v))
}

// EndedAtNEQ applies the NEQ predicate on the "ended_at" field.
func EndedAtNEQ(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNEQ(FieldEndedAt, v))
}

// EndedAtIn applies the In predicate on the "ended_at" field.
func EndedAtIn(vs ...time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldIn(FieldEndedAt, vs...))
}

// EndedAtNotIn applies the NotIn predicate on the "ended_at" field.
func EndedAtNotIn(vs ...time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNotIn(FieldEndedAt, vs...))
}

// EndedAtGT applies the GT predicate on the "ended_at" field.
func EndedAtGT(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldGT(FieldEndedAt, v))
}

// EndedAtGTE applies the GTE predicate on the "ended_at" field.
func EndedAtGTE(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldGTE(FieldEndedAt, v))
}

// EndedAtLT applies the LT predicate on the "ended_at" field.
func EndedAtLT(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldLT(FieldEndedAt, v))
}

// EndedAtLTE applies the LTE predicate on the "ended_at" field.
func EndedAtLTE(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldLTE(FieldEndedAt, v))
}

// EndedAtIsNil applies the IsNil predicate on the "ended_at" field.
func EndedAtIsNil() predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldIsNull(FieldEndedAt))
}

// EndedAtNotNil applies the NotNil predicate on the "ended_at" field.
func EndedAtNotNil() predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNotNull(FieldEndedAt))
}

// UnsatisfiedReasonEQ applies the EQ predicate on the "unsatisfied_reason" field.
func UnsatisfiedReasonEQ(v string) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldUnsatisfiedReason, v))
}

// UnsatisfiedReasonNEQ applies the NEQ predicate on the "unsatisfied_reason" field.
func UnsatisfiedReasonNEQ(v string) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNEQ(FieldUnsatisfiedReason, v))
}

// UnsatisfiedReasonIn applies the In predicate on the "unsatisfied_reason" field.
func UnsatisfiedReasonIn(vs ...string) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldIn(FieldUnsatisfiedReason, vs...))
}

// UnsatisfiedReasonNotIn applies the NotIn predicate on the "unsatisfied_reason" field.
func UnsatisfiedReasonNotIn(vs ...string) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNotIn(FieldUnsatisfiedReason, vs...))
}

// UnsatisfiedReasonGT applies the GT predicate on the "unsatisfied_reason" field.
func UnsatisfiedReasonGT(v string) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldGT(FieldUnsatisfiedReason, v))
}

// UnsatisfiedReasonGTE applies the GTE predicate on the "unsatisfied_reason" field.
func UnsatisfiedReasonGTE(v string) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldGTE(FieldUnsatisfiedReason, v))
}

// UnsatisfiedReasonLT applies the LT predicate on the "unsatisfied_reason" field.
func UnsatisfiedReasonLT(v string) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldLT(FieldUnsatisfiedReason, v))
}

// UnsatisfiedReasonLTE applies the LTE predicate on the "unsatisfied_reason" field.
func UnsatisfiedReasonLTE(v string) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldLTE(FieldUnsatisfiedReason, v))
}

// UnsatisfiedReasonContains applies the Contains predicate on the "unsatisfied_reason" field.
func UnsatisfiedReasonContains(v string) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldContains(FieldUnsatisfiedReason, v))
}

// UnsatisfiedReasonHasPrefix applies the HasPrefix predicate on the "unsatisfied_reason" field.
func UnsatisfiedReasonHasPrefix(v string) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldHasPrefix(FieldUnsatisfiedReason, v))
}

// UnsatisfiedReasonHasSuffix applies the HasSuffix predicate on the "unsatisfied_reason" field.
func UnsatisfiedReasonHasSuffix(v string) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldHasSuffix(FieldUnsatisfiedReason, v))
}

// UnsatisfiedReasonIsNil applies the IsNil predicate on the "unsatisfied_reason" field.
func UnsatisfiedReasonIsNil() predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldIsNull(FieldUnsatisfiedReason))
}

// UnsatisfiedReasonNotNil applies the NotNil predicate on the "unsatisfied_reason" field.
func UnsatisfiedReasonNotNil() predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNotNull(FieldUnsatisfiedReason))
}

// UnsatisfiedReasonEqualFold applies the EqualFold predicate on the "unsatisfied_reason" field.
func UnsatisfiedReasonEqualFold(v string) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEqualFold(FieldUnsatisfiedReason, v))
}

// UnsatisfiedReasonContainsFold applies the ContainsFold predicate on the "unsatisfied_reason" field.
func UnsatisfiedReasonContainsFold(v string) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldContainsFold(FieldUnsatisfiedReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.RedemptionOrder {
	return predicate.RedemptionOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReward applies the HasEdge predicate on the "reward" edge.
func HasReward() predicate.RedemptionOrder {
	return predicate.RedemptionOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, RewardTable, RewardColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRewardWith applies the HasEdge predicate on the "reward" edge with a given conditions (other predicates).
func HasRewardWith(preds ...predicate.Reward) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(func(s *sql.Selector) {
		step := newRewardStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasConsumer applies the HasEdge predicate on the "consumer" edge.
func HasConsumer() predicate.RedemptionOrder {
	return predicate.RedemptionOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ConsumerTable, ConsumerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasConsumerWith applies the HasEdge predicate on the "consumer" edge with a given conditions (other predicates).
func HasConsumerWith(preds ...predicate.User) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(func(s *sql.Selector) {
		step := newConsumerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProvider applies the HasEdge predicate on the "provider" edge.
func HasProvider() predicate.RedemptionOrder {
	return predicate.RedemptionOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ProviderTable, ProviderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProviderWith applies the HasEdge predicate on the "provider" edge with a given conditions (other predicates).
func HasProviderWith(preds ...predicate.User) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(func(s *sql.Selector) {
		step := newProviderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RedemptionOrder) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RedemptionOrder) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RedemptionOrder) predicate.RedemptionOrder {
	return predicate.RedemptionOrder(sql.NotPredicates(p))
}
