// Code generated by ent, DO NOT EDIT.

package agreementcompletion

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the agreementcompletion type in the database.
	Label = "agreement_completion"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldAgreementID holds the string denoting the agreement_id field in the database.
	FieldAgreementID = "agreement_id"
	// FieldCompleterID holds the string denoting the completer_id field in the database.
	FieldCompleterID = "completer_id"
	// FieldRecorderID holds the string denoting the recorder_id field in the database.
	FieldRecorderID = "recorder_id"
	// FieldPoints holds the string denoting the points field in the database.
	FieldPoints = "points"
	// FieldRequireConfirmation holds the string denoting the require_confirmation field in the database.
	FieldRequireConfirmation = "require_confirmation"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldRejectedReason holds the string denoting the rejected_reason field in the database.
	FieldRejectedReason = "rejected_reason"
	// FieldConfirmedBy holds the string denoting the confirmed_by field in the database.
	FieldConfirmedBy = "confirmed_by"
	// FieldConfirmedAt holds the string denoting the confirmed_at field in the database.
	FieldConfirmedAt = "confirmed_at"
	// FieldRejectedAt holds the string denoting the rejected_at field in the database.
	FieldRejectedAt = "rejected_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// EdgeAgreement holds the string denoting the agreement edge name in mutations.
	EdgeAgreement = "agreement"
	// EdgeCompleter holds the string denoting the completer edge name in mutations.
	EdgeCompleter = "completer"
	// EdgeRecorder holds the string denoting the recorder edge name in mutations.
	EdgeRecorder = "recorder"
	// EdgeConfirmer holds the string denoting the confirmer edge name in mutations.
	EdgeConfirmer = "confirmer"
	// Table holds the table name of the agreementcompletion in the database.
	Table = "agreement_completions"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "agreement_completions"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
	// AgreementTable is the table that holds the agreement relation/edge.
	AgreementTable = "agreement_completions"
	// AgreementInverseTable is the table name for the Agreement entity.
	// It exists in this package in order to avoid circular dependency with the "agreement" package.
	AgreementInverseTable = "agreements"
	// AgreementColumn is the table column denoting the agreement relation/edge.
	AgreementColumn = "agreement_id"
	// CompleterTable is the table that holds the completer relation/edge.
	CompleterTable = "agreement_completions"
	// CompleterInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	CompleterInverseTable = "users"
	// CompleterColumn is the table column denoting the completer relation/edge.
	CompleterColumn = "completer_id"
	// RecorderTable is the table that holds the recorder relation/edge.
	RecorderTable = "agreement_completions"
	// RecorderInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	RecorderInverseTable = "users"
	// RecorderColumn is the table column denoting the recorder relation/edge.
	RecorderColumn = "recorder_id"
	// ConfirmerTable is the table that holds the confirmer relation/edge.
	ConfirmerTable = "agreement_completions"
	// ConfirmerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ConfirmerInverseTable = "users"
	// ConfirmerColumn is the table column denoting the confirmer relation/edge.
	ConfirmerColumn = "confirmed_by"
)

// Columns holds all SQL columns for agreementcompletion fields.
var Columns = []string{
	FieldID,
	FieldGroupID,
	FieldAgreementID,
	FieldCompleterID,
	FieldRecorderID,
	FieldPoints,
	FieldRequireConfirmation,
	FieldStatus,
	FieldRejectedReason,
	FieldConfirmedBy,
	FieldConfirmedAt,
	FieldRejectedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRequireConfirmation holds the default value on creation for the "require_confirmation" field.
	DefaultRequireConfirmation bool
	// RejectedReasonValidator is a validator for the "rejected_reason" field. It is called by the builders before save.
	RejectedReasonValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending   Status = "pending"
	StatusConfirmed Status = "confirmed"
	StatusRejected  Status = "rejected"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusConfirmed, StatusRejected:
		return nil
	default:
		return fmt.Errorf("agreementcompletion: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the AgreementCompletion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByAgreementID orders the results by the agreement_id field.
func ByAgreementID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgreementID, opts...).ToFunc()
}

// ByCompleterID orders the results by the completer_id field.
func ByCompleterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompleterID, opts...).ToFunc()
}

// ByRecorderID orders the results by the recorder_id field.
func ByRecorderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecorderID, opts...).ToFunc()
}

// ByPoints orders the results by the points field.
func ByPoints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPoints, opts...).ToFunc()
}

// ByRequireConfirmation orders the results by the require_confirmation field.
func ByRequireConfirmation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequireConfirmation, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByRejectedReason orders the results by the rejected_reason field.
func ByRejectedReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRejectedReason, opts...).ToFunc()
}

// ByConfirmedBy orders the results by the confirmed_by field.
func ByConfirmedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfirmedBy, opts...).ToFunc()
}

// ByConfirmedAt orders the results by the confirmed_at field.
func ByConfirmedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfirmedAt, opts...).ToFunc()
}

// ByRejectedAt orders the results by the rejected_at field.
func ByRejectedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRejectedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByAgreementField orders the results by agreement field.
func ByAgreementField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAgreementStep(), sql.OrderByField(field, opts...))
	}
}

// ByCompleterField orders the results by completer field.
func ByCompleterField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCompleterStep(), sql.OrderByField(field, opts...))
	}
}

// ByRecorderField orders the results by recorder field.
func ByRecorderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRecorderStep(), sql.OrderByField(field, opts...))
	}
}

// ByConfirmerField orders the results by confirmer field.
func ByConfirmerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newConfirmerStep(), sql.OrderByField(field, opts...))
	}
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
	)
}
func newAgreementStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AgreementInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, AgreementTable, AgreementColumn),
	)
}
func newCompleterStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CompleterInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, CompleterTable, CompleterColumn),
	)
}
func newRecorderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RecorderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, RecorderTable, RecorderColumn),
	)
}
func newConfirmerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ConfirmerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ConfirmerTable, ConfirmerColumn),
	)
}
