// Code generated by ent, DO NOT EDIT.

package reward

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the reward type in the database.
	Label = "reward"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCostPoints holds the string denoting the cost_points field in the database.
	FieldCostPoints = "cost_points"
	// FieldCoverImageURL holds the string denoting the cover_image_url field in the database.
	FieldCoverImageURL = "cover_image_url"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldAutoFulfill holds the string denoting the auto_fulfill field in the database.
	FieldAutoFulfill = "auto_fulfill"
	// FieldAutoComplete holds the string denoting the auto_complete field in the database.
	FieldAutoComplete = "auto_complete"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldProviderID holds the string denoting the provider_id field in the database.
	FieldProviderID = "provider_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// EdgeProvider holds the string denoting the provider edge name in mutations.
	EdgeProvider = "provider"
	// EdgePinnedBy holds the string denoting the pinned_by edge name in mutations.
	EdgePinnedBy = "pinned_by"
	// Table holds the table name of the reward in the database.
	Table = "rewards"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "rewards"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
	// ProviderTable is the table that holds the provider relation/edge.
	ProviderTable = "rewards"
	// ProviderInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ProviderInverseTable = "users"
	// ProviderColumn is the table column denoting the provider relation/edge.
	ProviderColumn = "provider_id"
	// PinnedByTable is the table that holds the pinned_by relation/edge. The primary key declared below.
	PinnedByTable = "user_pinned_rewards"
	// PinnedByInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	PinnedByInverseTable = "users"
)

// Columns holds all SQL columns for reward fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldCostPoints,
	FieldCoverImageURL,
	FieldStatus,
	FieldAutoFulfill,
	FieldAutoComplete,
	FieldGroupID,
	FieldProviderID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// PinnedByPrimaryKey and PinnedByColumn2 are the table columns denoting the
	// primary key for the pinned_by relation (M2M).
	PinnedByPrimaryKey = []string{"user_id", "reward_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// CostPointsValidator is a validator for the "cost_points" field. It is called by the builders before save.
	CostPointsValidator func(int) error
	// DefaultAutoFulfill holds the default value on creation for the "auto_fulfill" field.
	DefaultAutoFulfill bool
	// DefaultAutoComplete holds the default value on creation for the "auto_complete" field.
	DefaultAutoComplete bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive   Status = "active"
	StatusInactive Status = "inactive"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusInactive:
		return nil
	default:
		return fmt.Errorf("reward: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Reward queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCostPoints orders the results by the cost_points field.
func ByCostPoints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostPoints, opts...).ToFunc()
}

// ByCoverImageURL orders the results by the cover_image_url field.
func ByCoverImageURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCoverImageURL, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByAutoFulfill orders the results by the auto_fulfill field.
func ByAutoFulfill(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAutoFulfill, opts...).ToFunc()
}

// ByAutoComplete orders the results by the auto_complete field.
func ByAutoComplete(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAutoComplete, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByProviderID orders the results by the provider_id field.
func ByProviderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByProviderField orders the results by provider field.
func ByProviderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProviderStep(), sql.OrderByField(field, opts...))
	}
}

// ByPinnedByCount orders the results by pinned_by count.
func ByPinnedByCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPinnedByStep(), opts...)
	}
}

// ByPinnedBy orders the results by pinned_by terms.
func ByPinnedBy(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPinnedByStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
	)
}
func newProviderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProviderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ProviderTable, ProviderColumn),
	)
}
func newPinnedByStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PinnedByInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, PinnedByTable, PinnedByPrimaryKey...),
	)
}
