// Code generated by ent, DO NOT EDIT.

package reward

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/way2we/way2we_api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Reward {
	return predicate.Reward(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Reward {
	return predicate.Reward(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Reward {
	return predicate.Reward(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Reward {
	return predicate.Reward(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Reward {
	return predicate.Reward(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Reward {
	return predicate.Reward(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Reward {
	return predicate.Reward(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Reward {
	return predicate.Reward(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Reward {
	return predicate.Reward(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Reward {
	return predicate.Reward(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Reward {
	return predicate.Reward(sql.FieldEQ(FieldDescription, v))
}

// CostPoints applies equality check predicate on the "cost_points" field. It's identical to CostPointsEQ.
func CostPoints(v int) predicate.Reward {
	return predicate.Reward(sql.FieldEQ(FieldCostPoints, v))
}

// CoverImageURL applies equality check predicate on the "cover_image_url" field. It's identical to CoverImageURLEQ.
func CoverImageURL(v string) predicate.Reward {
	return predicate.Reward(sql.FieldEQ(FieldCoverImageURL, v))
}

// AutoFulfill applies equality check predicate on the "auto_fulfill" field. It's identical to AutoFulfillEQ.
func AutoFulfill(v bool) predicate.Reward {
	return predicate.Reward(sql.FieldEQ(FieldAutoFulfill, v))
}

// AutoComplete applies equality check predicate on the "auto_complete" field. It's identical to AutoCompleteEQ.
func AutoComplete(v bool) predicate.Reward {
	return predicate.Reward(sql.FieldEQ(FieldAutoComplete, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int) predicate.Reward {
	return predicate.Reward(sql.FieldEQ(FieldGroupID, v))
}

// ProviderID applies equality check predicate on the "provider_id" field. It's identical to ProviderIDEQ.
func ProviderID(v int) predicate.Reward {
	return predicate.Reward(sql.FieldEQ(FieldProviderID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Reward {
	return predicate.Reward(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Reward {
	return predicate.Reward(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Reward {
	return predicate.Reward(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Reward {
	return predicate.Reward(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Reward {
	return predicate.Reward(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Reward {
	return predicate.Reward(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Reward {
	return predicate.Reward(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Reward {
	return predicate.Reward(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Reward {
	return predicate.Reward(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Reward {
	return predicate.Reward(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Reward {
	return predicate.Reward(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Reward {
	return predicate.Reward(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Reward {
	return predicate.Reward(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Reward {
	return predicate.Reward(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Reward {
	return predicate.Reward(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Reward {
	return predicate.Reward(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Reward {
	return predicate.Reward(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Reward {
	return predicate.Reward(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Reward {
	return predicate.Reward(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Reward {
	return predicate.Reward(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Reward {
	return predicate.Reward(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Reward {
	return predicate.Reward(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Reward {
	return predicate.Reward(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Reward {
	return predicate.Reward(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Reward {
	return predicate.Reward(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Reward {
	return predicate.Reward(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Reward {
	return predicate.Reward(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Reward {
	return predicate.Reward(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Reward {
	return predicate.Reward(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Reward {
	return predicate.Reward(sql.FieldContainsFold(FieldDescription, v))
}

// CostPointsEQ applies the EQ predicate on the "cost_points" field.
func CostPointsEQ(v int) predicate.Reward {
	return predicate.Reward(sql.FieldEQ(FieldCostPoints, v))
}

// CostPointsNEQ applies the NEQ predicate on the "cost_points" field.
func CostPointsNEQ(v int) predicate.Reward {
	return predicate.Reward(sql.FieldNEQ(FieldCostPoints, v))
}

// CostPointsIn applies the In predicate on the "cost_points" field.
func CostPointsIn(vs ...int) predicate.Reward {
	return predicate.Reward(sql.FieldIn(FieldCostPoints, vs...))
}

// CostPointsNotIn applies the NotIn predicate on the "cost_points" field.
func CostPointsNotIn(vs ...int) predicate.Reward {
	return predicate.Reward(sql.FieldNotIn(FieldCostPoints, vs...))
}

// CostPointsGT applies the GT predicate on the "cost_points" field.
func CostPointsGT(v int) predicate.Reward {
	return predicate.Reward(sql.FieldGT(FieldCostPoints, v))
}

// CostPointsGTE applies the GTE predicate on the "cost_points" field.
func CostPointsGTE(v int) predicate.Reward {
	return predicate.Reward(sql.FieldGTE(FieldCostPoints, v))
}

// CostPointsLT applies the LT predicate on the "cost_points" field.
func CostPointsLT(v int) predicate.Reward {
	return predicate.Reward(sql.FieldLT(FieldCostPoints, v))
}

// CostPointsLTE applies the LTE predicate on the "cost_points" field.
func CostPointsLTE(v int) predicate.Reward {
	return predicate.Reward(sql.FieldLTE(FieldCostPoints, v))
}

// CoverImageURLEQ applies the EQ predicate on the "cover_image_url" field.
func CoverImageURLEQ(v string) predicate.Reward {
	return predicate.Reward(sql.FieldEQ(FieldCoverImageURL, v))
}

// CoverImageURLNEQ applies the NEQ predicate on the "cover_image_url" field.
func CoverImageURLNEQ(v string) predicate.Reward {
	return predicate.Reward(sql.FieldNEQ(FieldCoverImageURL, v))
}

// CoverImageURLIn applies the In predicate on the "cover_image_url" field.
func CoverImageURLIn(vs ...string) predicate.Reward {
	return predicate.Reward(sql.FieldIn(FieldCoverImageURL, vs...))
}

// CoverImageURLNotIn applies the NotIn predicate on the "cover_image_url" field.
func CoverImageURLNotIn(vs ...string) predicate.Reward {
	return predicate.Reward(sql.FieldNotIn(FieldCoverImageURL, vs...))
}

// CoverImageURLGT applies the GT predicate on the "cover_image_url" field.
func CoverImageURLGT(v string) predicate.Reward {
	return predicate.Reward(sql.FieldGT(FieldCoverImageURL, v))
}

// CoverImageURLGTE applies the GTE predicate on the "cover_image_url" field.
func CoverImageURLGTE(v string) predicate.Reward {
	return predicate.Reward(sql.FieldGTE(FieldCoverImageURL, v))
}

// CoverImageURLLT applies the LT predicate on the "cover_image_url" field.
func CoverImageURLLT(v string) predicate.Reward {
	return predicate.Reward(sql.FieldLT(FieldCoverImageURL, v))
}

// CoverImageURLLTE applies the LTE predicate on the "cover_image_url" field.
func CoverImageURLLTE(v string) predicate.Reward {
	return predicate.Reward(sql.FieldLTE(FieldCoverImageURL, v))
}

// CoverImageURLContains applies the Contains predicate on the "cover_image_url" field.
func CoverImageURLContains(v string) predicate.Reward {
	return predicate.Reward(sql.FieldContains(FieldCoverImageURL, v))
}

// CoverImageURLHasPrefix applies the HasPrefix predicate on the "cover_image_url" field.
func CoverImageURLHasPrefix(v string) predicate.Reward {
	return predicate.Reward(sql.FieldHasPrefix(FieldCoverImageURL, v))
}

// CoverImageURLHasSuffix applies the HasSuffix predicate on the "cover_image_url" field.
func CoverImageURLHasSuffix(v string) predicate.Reward {
	return predicate.Reward(sql.FieldHasSuffix(FieldCoverImageURL, v))
}

// CoverImageURLIsNil applies the IsNil predicate on the "cover_image_url" field.
func CoverImageURLIsNil() predicate.Reward {
	return predicate.Reward(sql.FieldIsNull(FieldCoverImageURL))
}

// CoverImageURLNotNil applies the NotNil predicate on the "cover_image_url" field.
func CoverImageURLNotNil() predicate.Reward {
	return predicate.Reward(sql.FieldNotNull(FieldCoverImageURL))
}

// CoverImageURLEqualFold applies the EqualFold predicate on the "cover_image_url" field.
func CoverImageURLEqualFold(v string) predicate.Reward {
	return predicate.Reward(sql.FieldEqualFold(FieldCoverImageURL, v))
}

// CoverImageURLContainsFold applies the ContainsFold predicate on the "cover_image_url" field.
func CoverImageURLContainsFold(v string) predicate.Reward {
	return predicate.Reward(sql.FieldContainsFold(FieldCoverImageURL, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Reward {
	return predicate.Reward(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Reward {
	return predicate.Reward(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Reward {
	return predicate.Reward(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Reward {
	return predicate.Reward(sql.FieldNotIn(FieldStatus, vs...))
}

// AutoFulfillEQ applies the EQ predicate on the "auto_fulfill" field.
func AutoFulfillEQ(v bool) predicate.Reward {
	return predicate.Reward(sql.FieldEQ(FieldAutoFulfill, v))
}

// AutoFulfillNEQ applies the NEQ predicate on the "auto_fulfill" field.
func AutoFulfillNEQ(v bool) predicate.Reward {
	return predicate.Reward(sql.FieldNEQ(FieldAutoFulfill, v))
}

// AutoCompleteEQ applies the EQ predicate on the "auto_complete" field.
func AutoCompleteEQ(v bool) predicate.Reward {
	return predicate.Reward(sql.FieldEQ(FieldAutoComplete, v))
}

// AutoCompleteNEQ applies the NEQ predicate on the "auto_complete" field.
func AutoCompleteNEQ(v bool) predicate.Reward {
	return predicate.Reward(sql.FieldNEQ(FieldAutoComplete, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int) predicate.Reward {
	return predicate.Reward(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int) predicate.Reward {
	return predicate.Reward(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int) predicate.Reward {
	return predicate.Reward(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int) predicate.Reward {
	return predicate.Reward(sql.FieldNotIn(FieldGroupID, vs...))
}

// ProviderIDEQ applies the EQ predicate on the "provider_id" field.
func ProviderIDEQ(v int) predicate.Reward {
	return predicate.Reward(sql.FieldEQ(FieldProviderID, v))
}

// ProviderIDNEQ applies the NEQ predicate on the "provider_id" field.
func ProviderIDNEQ(v int) predicate.Reward {
	return predicate.Reward(sql.FieldNEQ(FieldProviderID, v))
}

// ProviderIDIn applies the In predicate on the "provider_id" field.
func ProviderIDIn(vs ...int) predicate.Reward {
	return predicate.Reward(sql.FieldIn(FieldProviderID, vs...))
}

// ProviderIDNotIn applies the NotIn predicate on the "provider_id" field.
func ProviderIDNotIn(vs ...int) predicate.Reward {
	return predicate.Reward(sql.FieldNotIn(FieldProviderID, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Reward {
	return predicate.Reward(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Reward {
	return predicate.Reward(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Reward {
	return predicate.Reward(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Reward {
	return predicate.Reward(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Reward {
	return predicate.Reward(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Reward {
	return predicate.Reward(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Reward {
	return predicate.Reward(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Reward {
	return predicate.Reward(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Reward {
	return predicate.Reward(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Reward {
	return predicate.Reward(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Reward {
	return predicate.Reward(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Reward {
	return predicate.Reward(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Reward {
	return predicate.Reward(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Reward {
	return predicate.Reward(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Reward {
	return predicate.Reward(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Reward {
	return predicate.Reward(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.Reward {
	return predicate.Reward(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.Reward {
	return predicate.Reward(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProvider applies the HasEdge predicate on the "provider" edge.
func HasProvider() predicate.Reward {
	return predicate.Reward(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ProviderTable, ProviderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProviderWith applies the HasEdge predicate on the "provider" edge with a given conditions (other predicates).
func HasProviderWith(preds ...predicate.User) predicate.Reward {
	return predicate.Reward(func(s *sql.Selector) {
		step := newProviderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Reward) predicate.Reward {
	return predicate.Reward(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Reward) predicate.Reward {
	return predicate.Reward(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Reward) predicate.Reward {
	return predicate.Reward(sql.NotPredicates(p))
}
