name: way2we_app
description: Way2We - Relationship Interaction App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  google_fonts: ^6.2.1
  image_picker: ^1.2.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  share_plus: ^10.1.4

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.2
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  generate: true
  uses-material-design: true
