// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AgreementsColumns holds the columns for the "agreements" table.
	AgreementsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 50},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 200},
		{Name: "points", Type: field.TypeInt},
		{Name: "require_confirmation", Type: field.TypeBool, Default: true},
		{Name: "cover_image_url", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "inactive"}, Default: "active"},
		{Name: "applicable_member_ids", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "creator_id", Type: field.TypeInt},
		{Name: "group_id", Type: field.TypeInt},
	}
	// AgreementsTable holds the schema information for the "agreements" table.
	AgreementsTable = &schema.Table{
		Name:       "agreements",
		Columns:    AgreementsColumns,
		PrimaryKey: []*schema.Column{AgreementsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "agreements_users_creator",
				Columns:    []*schema.Column{AgreementsColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "agreements_groups_agreements",
				Columns:    []*schema.Column{AgreementsColumns[11]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "agreement_group_id",
				Unique:  false,
				Columns: []*schema.Column{AgreementsColumns[11]},
			},
			{
				Name:    "agreement_group_id_status",
				Unique:  false,
				Columns: []*schema.Column{AgreementsColumns[11], AgreementsColumns[6]},
			},
		},
	}
	// GroupsColumns holds the columns for the "groups" table.
	GroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 30},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 200},
		{Name: "invitation_code", Type: field.TypeString, Unique: true, Nullable: true, Size: 6},
		{Name: "require_confirmation_default", Type: field.TypeBool, Default: true},
		{Name: "auto_complete_redemption_default", Type: field.TypeBool, Default: false},
		{Name: "auto_fulfill_redemption_default", Type: field.TypeBool, Default: false},
		{Name: "provider_incentive_ratio", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// GroupsTable holds the schema information for the "groups" table.
	GroupsTable = &schema.Table{
		Name:       "groups",
		Columns:    GroupsColumns,
		PrimaryKey: []*schema.Column{GroupsColumns[0]},
	}
	// GroupMembersColumns holds the columns for the "group_members" table.
	GroupMembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "member"}, Default: "member"},
		{Name: "joined_at", Type: field.TypeTime},
		{Name: "permissions", Type: field.TypeJSON, Nullable: true},
		{Name: "group_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// GroupMembersTable holds the schema information for the "group_members" table.
	GroupMembersTable = &schema.Table{
		Name:       "group_members",
		Columns:    GroupMembersColumns,
		PrimaryKey: []*schema.Column{GroupMembersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "group_members_groups_members",
				Columns:    []*schema.Column{GroupMembersColumns[4]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "group_members_users_user",
				Columns:    []*schema.Column{GroupMembersColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "groupmember_user_id_group_id",
				Unique:  true,
				Columns: []*schema.Column{GroupMembersColumns[5], GroupMembersColumns[4]},
			},
		},
	}
	// MemberSummariesColumns holds the columns for the "member_summaries" table.
	MemberSummariesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "balance", Type: field.TypeInt, Default: 0},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "group_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// MemberSummariesTable holds the schema information for the "member_summaries" table.
	MemberSummariesTable = &schema.Table{
		Name:       "member_summaries",
		Columns:    MemberSummariesColumns,
		PrimaryKey: []*schema.Column{MemberSummariesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "member_summaries_groups_member_summaries",
				Columns:    []*schema.Column{MemberSummariesColumns[3]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "member_summaries_users_member_summaries",
				Columns:    []*schema.Column{MemberSummariesColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "membersummary_group_id_user_id",
				Unique:  true,
				Columns: []*schema.Column{MemberSummariesColumns[3], MemberSummariesColumns[4]},
			},
		},
	}
	// PointLogsColumns holds the columns for the "point_logs" table.
	PointLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "delta", Type: field.TypeInt},
		{Name: "balance_after", Type: field.TypeInt},
		{Name: "reason", Type: field.TypeString, Nullable: true, Size: 200},
		{Name: "source_type", Type: field.TypeString, Size: 30},
		{Name: "source_id", Type: field.TypeString, Size: 64},
		{Name: "source_ref", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "group_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// PointLogsTable holds the schema information for the "point_logs" table.
	PointLogsTable = &schema.Table{
		Name:       "point_logs",
		Columns:    PointLogsColumns,
		PrimaryKey: []*schema.Column{PointLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "point_logs_groups_point_logs",
				Columns:    []*schema.Column{PointLogsColumns[8]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "point_logs_users_point_logs",
				Columns:    []*schema.Column{PointLogsColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "pointlog_group_id_source_type_source_id",
				Unique:  true,
				Columns: []*schema.Column{PointLogsColumns[8], PointLogsColumns[4], PointLogsColumns[5]},
			},
			{
				Name:    "pointlog_group_id_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{PointLogsColumns[8], PointLogsColumns[9], PointLogsColumns[7]},
			},
		},
	}
	// RewardsColumns holds the columns for the "rewards" table.
	RewardsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 50},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 200},
		{Name: "cost_points", Type: field.TypeInt},
		{Name: "cover_image_url", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "inactive"}, Default: "active"},
		{Name: "auto_fulfill", Type: field.TypeBool, Default: false},
		{Name: "auto_complete", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "group_id", Type: field.TypeInt},
		{Name: "provider_id", Type: field.TypeInt},
	}
	// RewardsTable holds the schema information for the "rewards" table.
	RewardsTable = &schema.Table{
		Name:       "rewards",
		Columns:    RewardsColumns,
		PrimaryKey: []*schema.Column{RewardsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "rewards_groups_rewards",
				Columns:    []*schema.Column{RewardsColumns[10]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "rewards_users_provider",
				Columns:    []*schema.Column{RewardsColumns[11]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "reward_group_id",
				Unique:  false,
				Columns: []*schema.Column{RewardsColumns[10]},
			},
			{
				Name:    "reward_group_id_status",
				Unique:  false,
				Columns: []*schema.Column{RewardsColumns[10], RewardsColumns[5]},
			},
		},
	}
	// TokenBlacklistsColumns holds the columns for the "token_blacklists" table.
	TokenBlacklistsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
	}
	// TokenBlacklistsTable holds the schema information for the "token_blacklists" table.
	TokenBlacklistsTable = &schema.Table{
		Name:       "token_blacklists",
		Columns:    TokenBlacklistsColumns,
		PrimaryKey: []*schema.Column{TokenBlacklistsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "nickname", Type: field.TypeString, Nullable: true, Size: 20},
		{Name: "avatar", Type: field.TypeString, Nullable: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserIdentitiesColumns holds the columns for the "user_identities" table.
	UserIdentitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"phone", "email", "wechat", "facebook", "apple"}},
		{Name: "identifier", Type: field.TypeString},
		{Name: "verified", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_identities", Type: field.TypeInt},
	}
	// UserIdentitiesTable holds the schema information for the "user_identities" table.
	UserIdentitiesTable = &schema.Table{
		Name:       "user_identities",
		Columns:    UserIdentitiesColumns,
		PrimaryKey: []*schema.Column{UserIdentitiesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_identities_users_identities",
				Columns:    []*schema.Column{UserIdentitiesColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "useridentity_type_identifier",
				Unique:  true,
				Columns: []*schema.Column{UserIdentitiesColumns[1], UserIdentitiesColumns[2]},
			},
		},
	}
	// UserPinnedAgreementsColumns holds the columns for the "user_pinned_agreements" table.
	UserPinnedAgreementsColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "agreement_id", Type: field.TypeInt},
	}
	// UserPinnedAgreementsTable holds the schema information for the "user_pinned_agreements" table.
	UserPinnedAgreementsTable = &schema.Table{
		Name:       "user_pinned_agreements",
		Columns:    UserPinnedAgreementsColumns,
		PrimaryKey: []*schema.Column{UserPinnedAgreementsColumns[0], UserPinnedAgreementsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_pinned_agreements_user_id",
				Columns:    []*schema.Column{UserPinnedAgreementsColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_pinned_agreements_agreement_id",
				Columns:    []*schema.Column{UserPinnedAgreementsColumns[1]},
				RefColumns: []*schema.Column{AgreementsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UserPinnedRewardsColumns holds the columns for the "user_pinned_rewards" table.
	UserPinnedRewardsColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "reward_id", Type: field.TypeInt},
	}
	// UserPinnedRewardsTable holds the schema information for the "user_pinned_rewards" table.
	UserPinnedRewardsTable = &schema.Table{
		Name:       "user_pinned_rewards",
		Columns:    UserPinnedRewardsColumns,
		PrimaryKey: []*schema.Column{UserPinnedRewardsColumns[0], UserPinnedRewardsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_pinned_rewards_user_id",
				Columns:    []*schema.Column{UserPinnedRewardsColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_pinned_rewards_reward_id",
				Columns:    []*schema.Column{UserPinnedRewardsColumns[1]},
				RefColumns: []*schema.Column{RewardsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AgreementsTable,
		GroupsTable,
		GroupMembersTable,
		MemberSummariesTable,
		PointLogsTable,
		RewardsTable,
		TokenBlacklistsTable,
		UsersTable,
		UserIdentitiesTable,
		UserPinnedAgreementsTable,
		UserPinnedRewardsTable,
	}
)

func init() {
	AgreementsTable.ForeignKeys[0].RefTable = UsersTable
	AgreementsTable.ForeignKeys[1].RefTable = GroupsTable
	GroupMembersTable.ForeignKeys[0].RefTable = GroupsTable
	GroupMembersTable.ForeignKeys[1].RefTable = UsersTable
	MemberSummariesTable.ForeignKeys[0].RefTable = GroupsTable
	MemberSummariesTable.ForeignKeys[1].RefTable = UsersTable
	PointLogsTable.ForeignKeys[0].RefTable = GroupsTable
	PointLogsTable.ForeignKeys[1].RefTable = UsersTable
	RewardsTable.ForeignKeys[0].RefTable = GroupsTable
	RewardsTable.ForeignKeys[1].RefTable = UsersTable
	UserIdentitiesTable.ForeignKeys[0].RefTable = UsersTable
	UserPinnedAgreementsTable.ForeignKeys[0].RefTable = UsersTable
	UserPinnedAgreementsTable.ForeignKeys[1].RefTable = AgreementsTable
	UserPinnedRewardsTable.ForeignKeys[0].RefTable = UsersTable
	UserPinnedRewardsTable.ForeignKeys[1].RefTable = RewardsTable
}
