// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AgreementsColumns holds the columns for the "agreements" table.
	AgreementsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 50},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 200},
		{Name: "points", Type: field.TypeInt},
		{Name: "require_confirmation", Type: field.TypeBool, Default: true},
		{Name: "cover_image_url", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "inactive"}, Default: "active"},
		{Name: "applicable_member_ids", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "creator_id", Type: field.TypeInt},
		{Name: "group_id", Type: field.TypeInt},
	}
	// AgreementsTable holds the schema information for the "agreements" table.
	AgreementsTable = &schema.Table{
		Name:       "agreements",
		Columns:    AgreementsColumns,
		PrimaryKey: []*schema.Column{AgreementsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "agreements_users_creator",
				Columns:    []*schema.Column{AgreementsColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "agreements_groups_agreements",
				Columns:    []*schema.Column{AgreementsColumns[11]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "agreement_group_id",
				Unique:  false,
				Columns: []*schema.Column{AgreementsColumns[11]},
			},
			{
				Name:    "agreement_group_id_status",
				Unique:  false,
				Columns: []*schema.Column{AgreementsColumns[11], AgreementsColumns[6]},
			},
		},
	}
	// GroupsColumns holds the columns for the "groups" table.
	GroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 30},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 200},
		{Name: "invitation_code", Type: field.TypeString, Unique: true, Nullable: true, Size: 6},
		{Name: "require_confirmation_default", Type: field.TypeBool, Default: true},
		{Name: "auto_complete_redemption_default", Type: field.TypeBool, Default: false},
		{Name: "auto_fulfill_redemption_default", Type: field.TypeBool, Default: false},
		{Name: "provider_incentive_ratio", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// GroupsTable holds the schema information for the "groups" table.
	GroupsTable = &schema.Table{
		Name:       "groups",
		Columns:    GroupsColumns,
		PrimaryKey: []*schema.Column{GroupsColumns[0]},
	}
	// GroupMembersColumns holds the columns for the "group_members" table.
	GroupMembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "member"}, Default: "member"},
		{Name: "joined_at", Type: field.TypeTime},
		{Name: "permissions", Type: field.TypeJSON, Nullable: true},
		{Name: "group_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// GroupMembersTable holds the schema information for the "group_members" table.
	GroupMembersTable = &schema.Table{
		Name:       "group_members",
		Columns:    GroupMembersColumns,
		PrimaryKey: []*schema.Column{GroupMembersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "group_members_groups_members",
				Columns:    []*schema.Column{GroupMembersColumns[4]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "group_members_users_user",
				Columns:    []*schema.Column{GroupMembersColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "groupmember_user_id_group_id",
				Unique:  true,
				Columns: []*schema.Column{GroupMembersColumns[5], GroupMembersColumns[4]},
			},
		},
	}
	// TokenBlacklistsColumns holds the columns for the "token_blacklists" table.
	TokenBlacklistsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
	}
	// TokenBlacklistsTable holds the schema information for the "token_blacklists" table.
	TokenBlacklistsTable = &schema.Table{
		Name:       "token_blacklists",
		Columns:    TokenBlacklistsColumns,
		PrimaryKey: []*schema.Column{TokenBlacklistsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "nickname", Type: field.TypeString, Nullable: true, Size: 20},
		{Name: "avatar", Type: field.TypeString, Nullable: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserIdentitiesColumns holds the columns for the "user_identities" table.
	UserIdentitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"phone", "email", "wechat", "facebook", "apple"}},
		{Name: "identifier", Type: field.TypeString},
		{Name: "verified", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_identities", Type: field.TypeInt},
	}
	// UserIdentitiesTable holds the schema information for the "user_identities" table.
	UserIdentitiesTable = &schema.Table{
		Name:       "user_identities",
		Columns:    UserIdentitiesColumns,
		PrimaryKey: []*schema.Column{UserIdentitiesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_identities_users_identities",
				Columns:    []*schema.Column{UserIdentitiesColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "useridentity_type_identifier",
				Unique:  true,
				Columns: []*schema.Column{UserIdentitiesColumns[1], UserIdentitiesColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AgreementsTable,
		GroupsTable,
		GroupMembersTable,
		TokenBlacklistsTable,
		UsersTable,
		UserIdentitiesTable,
	}
)

func init() {
	AgreementsTable.ForeignKeys[0].RefTable = UsersTable
	AgreementsTable.ForeignKeys[1].RefTable = GroupsTable
	GroupMembersTable.ForeignKeys[0].RefTable = GroupsTable
	GroupMembersTable.ForeignKeys[1].RefTable = UsersTable
	UserIdentitiesTable.ForeignKeys[0].RefTable = UsersTable
}
