// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Agreement is the predicate function for agreement builders.
type Agreement func(*sql.Selector)

// AgreementCompletion is the predicate function for agreementcompletion builders.
type AgreementCompletion func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// GroupMember is the predicate function for groupmember builders.
type GroupMember func(*sql.Selector)

// MemberSummary is the predicate function for membersummary builders.
type MemberSummary func(*sql.Selector)

// PointLog is the predicate function for pointlog builders.
type PointLog func(*sql.Selector)

// Reward is the predicate function for reward builders.
type Reward func(*sql.Selector)

// TokenBlacklist is the predicate function for tokenblacklist builders.
type TokenBlacklist func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserIdentity is the predicate function for useridentity builders.
type UserIdentity func(*sql.Selector)
